'use strict';
const router = require('express').Router();
const { verifyToken } = require('../../../../shared/middleware/auth');
const { requireFunc } = require('../../../../shared/middleware/permisos');
const c = require('../controllers/postventa.controller');

router.post('/sync',             verifyToken, c.sync);
router.post('/marcar-historico', verifyToken, c.marcarHistorico);
router.get('/config',       verifyToken, c.getConfig);
router.put('/config/:clave',verifyToken, requireFunc('postventa_mantenedores'), c.setConfig);
router.get('/perfiles-lista', verifyToken, c.getPerfiles);
router.get('/atribuciones',   verifyToken, c.getAtribuciones);
router.get('/alertas-config', verifyToken, c.getAlertasConfig);
router.put('/alertas-config', verifyToken, requireFunc('postventa_mantenedores'), c.setAlertasConfig);
router.get('/orden-pago',             verifyToken, c.getOrdenPago);
router.get('/orden-pago/:id/correlativo', verifyToken, c.correlativoOrden);
router.post('/orden-pago/emitir',     verifyToken, requireFunc('pv_orden_emitir'), c.emitirOrdenPago);
router.get('/saldos-a-pagar',       verifyToken, c.getSaldosAPagar);
router.get('/saldos-a-pagar/fondos',verifyToken, c.getFondos);
router.put('/saldos-a-pagar/fondos',verifyToken, requireFunc('pv_fondos_definir'), c.setFondos);
router.post('/saldos-a-pagar/enviar-a-pago', verifyToken, requireFunc('pv_saldos_seleccionar'), c.enviarAPago);
router.post('/saldos-a-pagar/pagar',verifyToken, requireFunc('postventa_saldos_pagar'), c.pagarSaldos);
router.post('/saldos-a-pagar/desmarcar', verifyToken, requireFunc('pv_saldos_revertir'), c.desmarcarSaldos);
// ── Flujo Comisión (espejo de Saldo Precio) ──
router.get('/atribuciones-comision', verifyToken, c.getAtribucionesComision);
router.get('/orden-pago-comision',          verifyToken, c.getOrdenPagoComision);
router.get('/orden-pago-comision/:id/correlativo', verifyToken, c.correlativoOrdenComision);
router.post('/orden-pago-comision/emitir',  verifyToken, requireFunc('pv_com_orden_emitir'), c.emitirOrdenPagoComision);
router.get('/comisiones-a-pagar',        verifyToken, c.getComisionesAPagar);
router.get('/comisiones-a-pagar/fondos', verifyToken, c.getFondosComision);
router.put('/comisiones-a-pagar/fondos', verifyToken, requireFunc('pv_com_fondos_definir'), c.setFondosComision);
router.post('/comisiones-a-pagar/enviar-a-pago', verifyToken, requireFunc('pv_com_seleccionar'), c.enviarAPagoComision);
router.post('/comisiones-a-pagar/pagar', verifyToken, requireFunc('pv_com_pagar'), c.pagarComisiones);
router.post('/comisiones-a-pagar/desmarcar', verifyToken, requireFunc('pv_com_revertir'), c.desmarcarComisiones);
router.get('/',               verifyToken, c.getAll);
router.put('/:id/etapa',    verifyToken, requireFunc('postventa_seguimiento'), c.setEtapa);
router.get('/:id/factura-comision', verifyToken, c.getFacturaComision);
router.put('/:id/factura-comision', verifyToken, requireFunc('postventa_seguimiento'), c.updateFacturaComision);

module.exports = router;
