'use strict';
/* ─────────────────────────────────────────────────────────────────────────────
   AYUDA CONTEXTUAL — seed 2: cobertura COMPLETA de páginas (2026-08-06).

   Cada entrada alimenta el panel "?" de su página (tabla ayuda_paginas).
   Se inserta con INSERT IGNORE: lo editado en el mantenedor Ayuda NUNCA se pisa.

   Formato corto:  r ruta · t título · i icono · d descripción (para qué sirve)
                   p pasos [[titulo, detalle]] · s submódulos [[nombre, para_qué]]
                   n siguiente (¿y después?)
   ───────────────────────────────────────────────────────────────────────────── */

module.exports = [

/* ═══ INICIO Y TRANSVERSALES ═══ */
{ r:'/mi-dia/', t:'Mi Día', i:'bi-sunrise', d:'Tu página de inicio personal: widgets con lo que te toca hoy — pendientes, indicadores, cumpleaños, agenda — según tu perfil.',
  p:[['Revisa tus widgets','Cada tarjeta muestra un frente distinto de tu día. Haz clic en cualquiera para ir al módulo de origen.'],['Personaliza (Admin)','Qué widget ve cada perfil se configura en Mantenedores → Panel Mi Día.']],
  n:'Los pendientes que aparecen acá salen de los módulos reales: gestionarlos allá los hace desaparecer de acá.' },
{ r:'/academia/', t:'Academia AutoFácil', i:'bi-mortarboard-fill', d:'Cursos de autocapacitación paso a paso: cada módulo del sistema es un curso, con tu avance guardado. Incluye los libros y el buscador Dónde·Cómo·Quién.',
  p:[['Elige un curso','Cada card es un módulo. Entra y avanza lección por lección; tu progreso queda guardado.'],['Consulta Dónde·Cómo·Quién','Pregunta con tus palabras dónde se hace algo, cómo y quién puede. Las respuestas salen de las reglas reales del sistema.']],
  n:'Si una búsqueda en Dónde·Cómo·Quién no te sirvió, queda anotada para que le escribamos la respuesta.' },
{ r:'/auditoria/', t:'Auditoría', i:'bi-clipboard-data', d:'Traza de quién hizo qué y cuándo en todo el sistema: cada acción crítica queda registrada con usuario, fecha, entidad y detalle.',
  p:[['Filtra por módulo, usuario o fecha','Acota la búsqueda a lo que investigas.'],['Abre el detalle','Cada fila muestra el antes/después del cambio cuando aplica.']],
  n:'Para la historia completa de UNA operación, usa mejor la Bitácora de un Crédito en Reportería.' },
{ r:'/certificados/', t:'Certificados', i:'bi-patch-check', d:'Emite certificados verificables (deuda, prepago y otros) con código QR y huella digital: cualquiera puede validar su autenticidad escaneando el QR.',
  p:[['Busca el crédito o cliente','El certificado se arma con los datos reales al momento de emitir.'],['Emite y descarga','El PDF sale con QR de verificación. Los textos se configuran en Mantenedores → Textos de Certificados.'],['Anula si corresponde','Un certificado emitido por error se anula (queda inválido al verificar), no se borra.']],
  n:'El cálculo de prepago usa el mismo motor que Caja y Aplicación de Fondos: siempre el mismo número.' },
{ r:'/donde-curso/', t:'¿Dónde Curso?', i:'bi-signpost-split-fill', d:'Veredicto rápido para el ejecutivo: dadas cuotas y saldo, dice por qué financiera conviene cursar (AutoFin o Unidad de Crédito) según rentabilidad y elegibilidad.',
  p:[['Ingresa cuotas y saldo','El sistema calcula la rentabilidad de cada lado con el motor real.'],['Lee el veredicto','AUTOFIN o UNIDAD si hay diferencia clara; "Decides Tú" si la diferencia es menor al umbral (da lo mismo para la empresa).']],
  n:'Después del curse, el informe Rentabilidad Créditos (Reportería) audita si se cursó por el lado más rentable.' },
{ r:'/simulador-rapido/', t:'Simulador Rápido', i:'bi-calculator-fill', d:'Cotización exprés en una pantalla: monto, plazo y al tiro la cuota. Pensado para responder al teléfono, con el mismo motor de cálculo del cotizador formal.',
  p:[['Ingresa monto y plazo','La cuota se calcula al instante con tasas y seguros vigentes.'],['Ajusta y compara','Mueve pie o plazo y mira cómo cambia la cuota.']],
  n:'Si el cliente se interesa, pasa a Cotizaciones para generar el documento formal.' },
{ r:'/ia/pregunta/', t:'Pregúntale a AutoFácil', i:'bi-chat-dots', d:'Consulta en lenguaje natural sobre los datos de la operación: preguntas como hablarías y la IA responde leyendo las tablas reales del sistema.',
  p:[['Escribe tu pregunta','Ej: "¿cuántas operaciones otorgamos este mes por dealer?".'],['Revisa la respuesta y su fuente','La respuesta indica de qué datos salió. Ante montos críticos, confirma en el módulo de origen.']],
  n:'Para reportes repetibles y exportables, usa Diseño de Consulta en Reportería.' },
{ r:'/politica/', t:'Política de Crédito', i:'bi-shield-check', d:'La Política de Crédito vigente publicada: reglas de evaluación, scorecard por quintiles y atribuciones. Es el documento normativo que aplica Evaluación Crediticia.',
  p:[['Consulta la regla','Navega por capítulos: sujetos de crédito, scorecard, atribuciones, excepciones.']],
  n:'La aplicación viva de estas reglas está en Evaluación Crediticia y en las Políticas de Preaprobación.' },
{ r:'/sistema/', t:'Sistema', i:'bi-gear', d:'Card contenedora del Dashboard principal y su configuración de pestañas.',
  p:[['Abre el Dashboard','El tablero de colocaciones con filtros por período e institución.']],
  n:'Las pestañas visibles por perfil se configuran con el permiso de dashboard_config.' },
{ r:'/pagos/', t:'Pagos', i:'bi-cash-stack', d:'Módulo histórico de registro de pagos. La operación de hoy vive en Tesorería: Caja (recaudación), ODP de Cuotas y Aplicación de Fondos.',
  p:[['Consulta lo histórico','Solo para revisar registros antiguos.']],
  n:'Para pagar cuotas hoy: Cobranza emite la ODP y Tesorería la procesa en su cola.' },
{ r:'/vehiculos/', t:'Vehículos', i:'bi-car-front-fill', d:'Catálogo de marcas y modelos que alimenta cotizaciones y créditos.',
  p:[['Consulta el catálogo','El bien financiado de cada operación referencia este catálogo.']],
  n:'La mantención (agregar marcas/modelos) se hace en Mantenedores → Vehículos.' },
{ r:'/credenciales/', t:'Credenciales Corporativas', i:'bi-person-badge', d:'Tu credencial corporativa digital: datos, foto y QR de verificación para identificarte como colaborador de AutoFácil.',
  p:[['Genera tu credencial','Con tu ficha al día, descárgala o muéstrala desde el teléfono.']],
  n:'Si tus datos están desactualizados, corrígelos primero en RRHH → Mi Ficha.' },
{ r:'/presentacion-grupo/', t:'Presentación Business Suite', i:'bi-easel2-fill', d:'La presentación institucional del sistema: qué es la Business Suite, sus módulos y cifras, lista para mostrar al grupo o a un tercero.',
  p:[['Navega las láminas','Avanza con las flechas; está pensada para proyectar.']],
  n:'La documentación completa vive en Mantenedores → Documentación Business Suite.' },
{ r:'/facilbook/', t:'Facilbook', i:'bi-facebook', d:'La red social interna: publicaciones, reacciones y reconocimientos entre colegas. Cultura, no operación.',
  p:[['Publica y reacciona','Comparte novedades y felicita a tus colegas.']],
  n:'Para avisos oficiales de la empresa está Soporte → Avisos en Línea.' },
{ r:'/cafe/', t:'Café', i:'bi-cup-hot-fill', d:'El espacio de pausa de la suite: juegos y comunidad. Sin efecto en los datos de negocio.',
  p:[['Tómate un café','Y vuelve con energía.']], n:null },
{ r:'/retirados/', t:'Retirados', i:'bi-archive', d:'Contenedor de funciones retiradas del flujo brokerage antiguo. Se conserva solo por trazabilidad; sin operación nueva.',
  p:[], n:'El flujo vigente de cartas y brokerage está en Cartas de Aprobación (/aprobaciones/).' },
{ r:'/cartas-aprobacion/', t:'Cartas de Aprobación (Antiguo)', i:'bi-envelope-check', d:'La primera generación del módulo de cartas y cartolas. Sigue disponible para consulta histórica; el flujo vivo es Cartas de Aprobación (/aprobaciones/).',
  p:[['Consulta lo histórico','Cartas y cartolas anteriores a la migración.']],
  n:'Toda carta nueva se crea en /aprobaciones/.' },
{ r:'/old-base-unica/', t:'Old Base Única', i:'bi-table', d:'La base histórica INDEXA (12.988 filas) para consulta: las operaciones anteriores a la migración, tal como venían en la planilla única.',
  p:[['Busca por RUT u operación','Solo lectura: es el archivo histórico.']],
  n:'Las operaciones migradas ya viven en Créditos; esto es el respaldo de origen.' },

/* ═══ CLIENTES ═══ */
{ r:'/antecedentes-laborales/', t:'Antecedentes Laborales', i:'bi-briefcase', d:'Situación laboral de cada cliente: empleador, renta, antigüedad y tipo de contrato. Fuente única — la evaluación y las cartas leen de aquí.',
  p:[['Busca por RUT','Cada cliente tiene una sola ficha laboral vigente.'],['Actualiza con respaldo','Al cambiar renta o empleador, adjunta el documento que lo respalda.']],
  n:'Con los antecedentes al día, la Evaluación Crediticia calcula bien la carga financiera.' },
{ r:'/informacion-comercial/', t:'Información Comercial', i:'bi-building', d:'Perfil de deudas del cliente: compromisos vigentes, morosidades e historial comercial. Fuente única para evaluación y cobranza.',
  p:[['Busca por RUT','Revisa deudas declaradas e informadas.'],['Actualiza el perfil','Registra cambios con su origen (informe, declaración).']],
  n:'Se complementa con los Informes DealerNet para el comportamiento externo.' },

/* ═══ EVALUACIÓN Y CURSE ═══ */
{ r:'/evaluacion-crediticia/', t:'Evaluación Crediticia', i:'bi-clipboard-pulse', d:'La puerta de entrada del negocio: con el RUT arma la ficha completa del cliente — datos, antecedentes, informes DealerNet y scorecard de la Política V3.0 — para decidir si la operación avanza.',
  p:[['Ingresa el RUT','El sistema trae todo lo que sabe del cliente y consulta DealerNet.'],['Revisa score y alertas','El scorecard por quintiles y las alertas de política se calculan solos.'],['Decide','Aprueba, rechaza o escala según tus atribuciones.']],
  s:[['Repositorio de Preaprobaciones','Las evaluaciones automáticas del Portal del Dealer y su resultado.'],['Score de Mora','Mora histórica por segmento: qué tan bien pagan perfiles similares.']],
  n:'Una evaluación aprobada continúa en el Generador de Cartas de Aprobación.' },
{ r:'/preaprobaciones/', t:'Repositorio de Preaprobaciones', i:'bi-patch-check', d:'Historial de las evaluaciones automáticas: cada consulta del Portal del Dealer queda aquí con su resultado y las reglas que aplicaron.',
  p:[['Filtra por dealer o fecha','Revisa qué se preaprobó y qué se rechazó automáticamente.'],['Abre el detalle','Cada fila muestra qué regla paramétrica decidió.']],
  n:'Las reglas se ajustan en Mantenedores → Políticas de Preaprobación.' },
{ r:'/score-mora/', t:'Score de Mora', i:'bi-graph-down', d:'Mora histórica por segmento: cómo han pagado realmente los clientes con un perfil dado. Alimenta la evaluación con evidencia propia.',
  p:[['Elige el segmento','Cruza variables (edad, renta, tipo de crédito) y mira su curva de mora.']],
  n:'Úsalo como referencia junto al scorecard de la Política, no en su reemplazo.' },
{ r:'/aprobaciones/detalle-mes/', t:'Detalle Mensual de Cartas', i:'bi-calendar3', d:'Vista consolidada del mes: todas las cartas emitidas con su desenlace (otorgada, desistida, vencida) y sus montos.',
  p:[['Elige el mes','La grilla muestra cada carta con su estado final.'],['Exporta','Baja el detalle para análisis o cuadratura.']],
  n:'Para el flujo de trabajo diario de cartas usa la vista principal de Aprobaciones.' },
{ r:'/creditos/anulaciones.html/', t:'Anular Operación', i:'bi-x-octagon', d:'Anulación formal de una operación con segregación de funciones: una persona solicita y OTRA aprueba. La anulación retira la comisión de la cartola y deja al crédito en etapa ANULADO.',
  p:[['Solicita la anulación','Indica la operación y el motivo. Requiere el permiso de solicitar.'],['Otra persona aprueba','Quien tenga el permiso de aprobar revisa y confirma. No puede ser el mismo solicitante.']],
  n:'Un anulado NO cuenta como rechazado: tiene su propia etapa y sale de las cartolas.' },
{ r:'/carga-masiva/digitacion/', t:'Digitación Datos Faltantes', i:'bi-pencil-square', d:'Cola compartida para completar los campos que faltan en operaciones cargadas: cada digitador toma un registro y queda bloqueado 20 minutos para que nadie lo pise.',
  p:[['Toma el siguiente','El sistema te asigna el registro y lo bloquea para ti.'],['Completa y guarda','Los campos faltantes están marcados. Al guardar, el registro sale de la cola.']],
  n:'Si no alcanzas a terminar, el bloqueo expira solo y otro puede tomarlo.' },
{ r:'/fundantes/', t:'Seguimiento Fundantes', i:'bi-folder-check', d:'Controla que los documentos fundantes del crédito (pagaré, contrato, mandatos) lleguen y se validen. Landing con las vistas de Ejecutivo y Operaciones.',
  p:[['Elige tu vista','Ejecutivo: lo que debes entregar. Operaciones: lo que debes recibir y validar.']],
  s:[['Seguimiento Ejecutivo','Tus operaciones con fundantes pendientes de entrega.'],['Operaciones','Recepción y validación de lo entregado.'],['Historial','Todo lo ya validado, con fechas y responsables.']],
  n:'Los tipos de documento exigidos se configuran en el mantenedor Documentos Fundantes.' },
{ r:'/fundantes-seguimiento/', t:'Fundantes — Ejecutivo', i:'bi-folder-check', d:'Tus operaciones con documentos fundantes pendientes: qué falta entregar de cada crédito otorgado.',
  p:[['Revisa tus pendientes','Cada operación lista los documentos que faltan.'],['Entrega y marca','Al entregar físicamente, Operaciones valida y el pendiente desaparece.']],
  n:'Operaciones valida en su propia vista; el historial guarda todo lo cerrado.' },
{ r:'/fundantes-operaciones/', t:'Fundantes — Operaciones', i:'bi-inboxes', d:'Recepción y validación de los documentos fundantes que entregan los ejecutivos.',
  p:[['Revisa lo recibido','Confirma que el documento corresponde y está completo.'],['Valida','Al validar queda registrado con tu nombre y fecha.']],
  n:'Lo validado pasa al Historial de Fundantes.' },
{ r:'/fundantes-seguimiento/historial/', t:'Historial de Fundantes', i:'bi-clock-history', d:'Todo lo ya validado: qué documento, de qué operación, quién lo validó y cuándo.',
  p:[['Busca por operación o fecha','Consulta de solo lectura para auditoría.']], n:null },

/* ═══ COBRANZA Y CLIENTE ═══ */
{ r:'/cobranza/prejudicial/', t:'Cobranza Pre-judicial', i:'bi-exclamation-triangle-fill', d:'La cartera morosa antes de acciones legales: gestiones, compromisos de pago y envíos al cliente cumpliendo la Ley 21.320.',
  p:[['Trabaja la cartera por tramo','Los casos se ordenan por días de mora y monto.'],['Registra cada gestión','Llamada, correo o visita: todo queda en la ficha del caso.'],['Emite la ODP si el cliente paga','La orden de pago de cuotas viaja a la cola de Tesorería.']],
  n:'Si el caso escala, pasa a Judicial con su expediente. Las automatizaciones (correo/WhatsApp por tramo) corren solas desde su mantenedor.' },
{ r:'/cobranza/judicial/', t:'Cobranza Judicial', i:'bi-file-earmark-text-fill', d:'Casos en sede judicial: demanda, abogado, tribunal y estado procesal de cada expediente.',
  p:[['Registra el expediente','Abogado, tribunal, rol de la causa y estado.'],['Actualiza los hitos','Cada avance procesal queda con fecha y responsable.']],
  n:'Los catálogos (abogados, tribunales, estados) se administran en Mantenedores → Cobranza Judicial.' },
{ r:'/cobranza/reporteria/', t:'Reportería Cobranzas', i:'bi-clipboard-data-fill', d:'Indicadores de la gestión de cobranza: mora por tramo, recuperación, gestiones realizadas y provisiones.',
  p:[['Elige el corte','Por período, tramo o gestor.'],['Exporta','Baja el detalle para el comité.']],
  n:'Las provisiones que ves acá son las mismas que contabiliza Tesorería → Provisiones + Castigos.' },
{ r:'/crm/gestiones/', t:'Gestiones de Contacto', i:'bi-telephone-fill', d:'La bitácora comercial: cada llamada, correo o visita a un cliente o prospecto queda tipificada aquí.',
  p:[['Registra la gestión','Tipo, resultado y comentario. Queda a tu nombre con fecha.'],['Consulta el historial','Antes de llamar, mira qué se conversó antes.']],
  n:'Las estadísticas del equipo salen solas de lo que registres: sin registro no hay medición.' },
{ r:'/crm/estadisticas/', t:'Estadísticas CRM', i:'bi-bar-chart-line', d:'Productividad de la gestión comercial: gestiones por usuario, resultados y conversión por campaña.',
  p:[['Filtra por período y usuario','Compara equipos y semanas.']],
  n:'Los datos salen de Gestiones de Contacto: la calidad de la estadística es la calidad del registro.' },
{ r:'/crm/campanas/', t:'Campañas de Outbound', i:'bi-megaphone-fill', d:'Campañas telefónicas: creas la campaña, cargas la base, la repartes entre ejecutivos y mides resultados.',
  p:[['Crea la campaña y carga la base','Define objetivo y sube los contactos.'],['Asigna y ejecuta','Cada ejecutivo recibe su lista; cada llamada se registra como gestión.'],['Mide','Los resultados por campaña quedan en Estadísticas.']],
  n:'Para envíos masivos por correo/WhatsApp usa Campañas Masivas.' },
{ r:'/campanas-ventas/', t:'Campañas de Venta (CRM)', i:'bi-telephone-outbound-fill', d:'El discador de campañas comerciales: toma la base asignada y llama contacto por contacto, registrando cada resultado sin salir de la pantalla.',
  p:[['Toma el siguiente contacto','El discador te muestra la ficha y el guion.'],['Registra el resultado','Interesado, no contesta, no interesado — queda como gestión CRM.']],
  n:'Un interesado sigue en Cotizaciones o Evaluación Crediticia.' },
{ r:'/campanas-masivas/', t:'Campañas Masivas', i:'bi-megaphone-fill', d:'Envíos masivos por correo y WhatsApp con grupos de control por deciles: una parte de la base no recibe el envío, para medir el efecto real de la campaña.',
  p:[['Arma la base y el mensaje','Sube o filtra los destinatarios y redacta la plantilla.'],['Define el decil de control','El sistema reserva el grupo que NO recibe, para comparar.'],['Envía y mide','Compara la respuesta de quienes recibieron contra el control.']],
  n:'En Modo Desarrollo todos los envíos se desvían a cuentas de prueba: nada sale al mundo real.' },
{ r:'/whatsapp/', t:'WhatsApp', i:'bi-whatsapp', d:'El canal WhatsApp corporativo: conversaciones atendidas por personas y el bot Facilito para respuestas automáticas.',
  p:[['Atiende las conversaciones','Las entrantes llegan al panel; respóndelas como un chat normal.'],['Deja que Facilito filtre','El bot responde lo frecuente y deriva a humano lo demás.']],
  s:[['Panel WhatsApp','Bandeja de conversaciones en vivo.'],['Seguimiento de Cartas','Avisos automáticos del estado de la carta por WhatsApp.']],
  n:'Las plantillas salientes requieren aprobación de Meta; la cobranza usa este mismo canal.' },
{ r:'/whatsapp/seguimiento-cartas.html/', t:'Seguimiento de Cartas por WhatsApp', i:'bi-whatsapp', d:'Avisos automáticos por WhatsApp del avance de la carta de aprobación al dealer/cliente.',
  p:[['Revisa los envíos','Qué carta avisó qué cosa y cuándo, con su estado de entrega.']],
  n:'El contenido de los mensajes es plantilla aprobada; no se edita por conversación.' },
{ r:'/atencion-remota/', t:'Atención Remota', i:'bi-headset', d:'Chat en vivo con clientes a distancia, con intercambio de documentos en la misma conversación.',
  p:[['Atiende el chat','Las sesiones entrantes aparecen en el panel.'],['Usa respuestas rápidas','Los textos frecuentes están precargados (Mantenedores → Respuestas Rápidas).'],['Recibe documentos','El cliente sube sus papeles por el mismo chat.']],
  n:'Los documentos recibidos quedan asociados al cliente para su evaluación.' },

/* ═══ TESORERÍA ═══ */
{ r:'/tesoreria/caja/', t:'Caja', i:'bi-cash-coin', d:'La caja operativa: recauda pagos presenciales de cuotas y prepagos, con comprobante timbrado al momento.',
  p:[['Abre tu caja','Solo puedes operar con una caja abierta a tu nombre.'],['Cobra','Busca la operación, selecciona cuotas o prepago (motor único de cálculo) y registra el pago.'],['Cuadra al cierre','Al final del turno, el cierre compara lo registrado contra lo recaudado.']],
  n:'Todo movimiento de caja genera su asiento contable automáticamente.' },
{ r:'/tesoreria/cajas/', t:'Administración de Cajas', i:'bi-cash-stack', d:'Gestión de las cajas físicas: crearlas, asignarlas a responsables y controlar su estado.',
  p:[['Crea o edita la caja','Nombre, responsable y estado.'],['Controla aperturas','Una caja abierta sin cierre es un pendiente de cuadratura.']],
  n:'El cierre diario se hace en Cierre de Caja.' },
{ r:'/tesoreria/cierre-caja/', t:'Cierre de Caja', i:'bi-journal-check', d:'La cuadratura diaria: compara lo registrado en el sistema contra lo efectivamente recaudado y cierra el turno.',
  p:[['Revisa el resumen del día','Movimientos, medios de pago y totales.'],['Declara lo contado','Si hay diferencia, queda explícita y con responsable.'],['Cierra','El cierre queda firmado y alimenta la contabilidad.']],
  n:'Una diferencia de caja no se arregla borrando: se documenta y se investiga.' },
{ r:'/tesoreria/cuentas-corrientes.html/', t:'Cuentas Corrientes', i:'bi-bank', d:'Los movimientos bancarios de cada cuenta corriente: carga cartolas sin duplicar y mira resúmenes de gastos e ingresos por período.',
  p:[['Carga la cartola','El botón "Cargar cartola" lee el Excel del banco y anexa SOLO los movimientos que no estaban.'],['Filtra y busca','Por fecha, texto o documento; la búsqueda no distingue mayúsculas ni tildes.'],['Mira los resúmenes','Las pestañas Gastos e Ingresos agrupan por concepto con su % del período.']],
  n:'Para cruzar estos movimientos contra las operaciones, usa Conciliación Bancaria.' },
{ r:'/tesoreria/conciliacion-bancaria/', t:'Conciliación Bancaria', i:'bi-check2-square', d:'Cruza los movimientos del banco contra lo registrado en el sistema (caja, ODP, contabilidad). Auto-concilia solo lo inequívoco: RUT en la glosa con un único candidato, o regla por descripción.',
  p:[['Carga o sincroniza movimientos','Desde cartola o Fintoc.'],['Ejecuta la conciliación automática','El sistema empareja lo seguro y deja lo dudoso para ti.'],['Concilia lo pendiente a mano','Cada match manual queda registrado con tu nombre.']],
  n:'Las reglas por descripción (ej: "COMISION MANTENCION" → gasto bancario) se administran en la misma página.' },
{ r:'/tesoreria/cuentas-transitorias/', t:'Cuentas Transitorias', i:'bi-arrow-left-right', d:'Las partidas puente: dinero que llegó al banco y aún no se aplica a su destino final (una operación, un pago). Nada debe envejecer aquí.',
  p:[['Revisa las partidas abiertas','Cada una con su antigüedad y origen.'],['Aplica a destino','Vincula la partida con su operación (JOIN por crédito) y ciérrala.']],
  n:'Una transitoria vieja es plata sin dueño: la meta es que la lista tienda a cero.' },
{ r:'/tesoreria/odp-cuotas/', t:'Órdenes de Pago de Cuotas (Cola)', i:'bi-inbox', d:'La cola de ODP emitidas desde Cobranza para pagar cuotas: Tesorería las procesa y confirma el pago.',
  p:[['Revisa la cola','Cada ODP trae operación, cuotas y monto.'],['Procesa y confirma','Al confirmar, las cuotas quedan pagadas y el asiento se genera solo.']],
  n:'La emisión nace en Cobranza; acá solo se procesa.' },
{ r:'/tesoreria/aplicacion-fondos/', t:'Aplicación de Fondos', i:'bi-cash-coin', d:'Aplica fondos recibidos a una operación con descuento por ítem sobre el motor de prepago: gastos, intereses y capital en el orden correcto, con firmas HECHO→PROCESADO.',
  p:[['Selecciona la operación y el monto','El motor de prepago calcula la distribución por ítem.'],['Ajusta descuentos por ítem','Cada condonación parcial queda explícita.'],['Firma el flujo','Quien hace no es quien procesa: dos firmas distintas.']],
  n:'El orden de condonación es regla de la casa: primero gastos, luego intereses; el capital nunca.' },
{ r:'/tesoreria/cierre-mes/', t:'Cierre de Mes', i:'bi-calendar2-check', d:'El checklist del cierre mensual: cada responsable marca su tarea y al final se pone el candado que congela el mes en todo el sistema.',
  p:[['Sigue el checklist','Cada ítem tiene responsable y estado; los recordatorios salen solos.'],['Cierra con el candado','Con todo OK, quien tiene el permiso cierra el mes: desde ahí nadie edita datos de ese período.']],
  n:'Un mes cerrado protege comisiones, créditos y contabilidad. Reabrir es excepción con auditoría.' },
{ r:'/tesoreria/cierre-contable/', t:'Cierre Contable', i:'bi-journal-check', d:'El informe mensual de cierre para el grupo (Ecuador): estados y cuadraturas del período ya cerrado.',
  p:[['Genera el informe del mes','Con el mes cerrado, el informe se arma con los datos congelados.'],['Revisa las cuadraturas','Operación vs contabilidad deben calzar antes de enviar.']],
  n:'Se alimenta del candado de Cierre de Mes y de la Contabilidad centralizada.' },
{ r:'/tesoreria/castigos/', t:'Provisiones + Castigos', i:'bi-file-earmark-minus', d:'Las provisiones de incobrables (cierre automático mensual) y los castigos de saldo con doble firma gerencial (Finanzas + Operaciones/Riesgo).',
  p:[['Revisa las provisiones del mes','Se calculan y contabilizan solas al cierre.'],['Gestiona los castigos','La solicitud nace en el crédito; acá se ve el historial y el estado de las firmas.']],
  n:'Un castigo no borra la deuda: la saca del activo y la cobranza puede seguir.' },
{ r:'/tesoreria/venta-cartera.html/', t:'Venta de Cartera', i:'bi-bag-check', d:'El traspaso de créditos de cartera propia (AUTOFACIL) a CFC: selección del stock, cuotas del mes y registro de la venta.',
  p:[['Arma el paquete','Selecciona las operaciones a vender según los criterios del acuerdo.'],['Registra la venta','El traspaso queda documentado y contabilizado.']],
  n:'Las cuotas vendidas dejan de ser flujo propio: revisa el efecto en los informes de cartera.' },
{ r:'/tesoreria/banco-conexiones/', t:'Conexiones Bancarias', i:'bi-bank2', d:'La integración con los bancos vía Fintoc: cuentas conectadas, sincronización de movimientos y estado de cada conexión.',
  p:[['Revisa el estado de las conexiones','Cada cuenta muestra su última sincronización.'],['Sincroniza','Trae los movimientos nuevos para conciliar.']],
  n:'Los movimientos sincronizados alimentan la Conciliación Bancaria.' },
{ r:'/tesoreria/bitacora/', t:'Bitácora de Transacciones', i:'bi-journal-text', d:'La traza de toda transacción de tesorería: quién, cuándo, cuánto y sobre qué operación.',
  p:[['Filtra por fecha, tipo o usuario','Consulta de solo lectura para control y auditoría.']], n:null },
{ r:'/tesoreria/saldo-proceso-pago/', t:'Saldo Precio en Proceso de Pago', i:'bi-hourglass-split', d:'Los saldos de precio que ya están en su circuito de pago: en qué paso va cada uno (fondos, nómina, orden, pagado).',
  p:[['Sigue el estado','Cada operación muestra su paso actual y responsable.']],
  n:'El circuito completo se opera desde Post Venta → Saldos Precios a Pagar.' },

/* ═══ ÓRDENES DE PAGO ═══ */
{ r:'/ordenes-pago/', t:'Órdenes de Pago', i:'bi-cash-stack', d:'El canal formal de egresos a proveedores: toda salida de plata a un tercero nace como una ODP con correlativo único.',
  p:[['Emite la orden','Proveedor, documento y monto. El devengo se contabiliza al registrar el documento.'],['Sigue el historial','Cada ODP con su estado y sus documentos.']],
  s:[['Emitir Orden de Pago','La emisión formal con correlativo OP-.'],['Historial','Todas las órdenes y su estado.'],['Base de Proveedores','La fuente única de proveedores.'],['Estadísticas de Compra','Cuánto y a quién se compra.']],
  n:'El pago posterior rebaja el pasivo contra banco: devengo y pago son dos hechos distintos.' },
{ r:'/ordenes-pago/emision/', t:'Emitir Orden de Pago', i:'bi-cash-stack', d:'Emisión de la ODP: proveedor, documento de respaldo, monto e imputación. El correlativo OP- lo asigna el sistema.',
  p:[['Elige el proveedor','Debe existir en la Base de Proveedores.'],['Registra el documento','Factura o boleta con su IVA/retención: el asiento de devengo sale solo.'],['Emite','La orden queda lista para su aprobación y pago.']],
  n:'Las compras internas aprobadas en Soporte terminan acá como ODP.' },
{ r:'/ordenes-pago/historial/', t:'Historial de Órdenes de Pago', i:'bi-clock-history', d:'Todas las ODP emitidas: estado, documentos, aprobaciones y pago.',
  p:[['Busca por proveedor, correlativo o fecha','Abre cada orden para ver su detalle y respaldos.']], n:null },
{ r:'/ordenes-pago/proveedores/', t:'Base de Proveedores', i:'bi-people', d:'La fuente única de proveedores: RUT, razón social, datos bancarios y giro. Toda ODP referencia esta base.',
  p:[['Crea o edita el proveedor','El RUT se valida; los datos bancarios son los del pago.']],
  n:'Un proveedor con datos bancarios malos es un pago devuelto: manténlos al día.' },
{ r:'/ordenes-pago/estadisticas/', t:'Estadísticas de Compra', i:'bi-bar-chart', d:'Cuánto se compra, a quién y en qué: gasto por proveedor, categoría y período.',
  p:[['Elige el corte','Por proveedor, mes o categoría.']],
  n:'Sirve de insumo para renegociar con los proveedores frecuentes.' },

/* ═══ POST VENTA ═══ */
{ r:'/postventa/comisiones-parques/', t:'Comisiones Parques a Pagar', i:'bi-signpost-2', d:'El circuito de pago de los parques: arriendo fijo mensual prorrateado entre las otorgadas del mes (nunca fee por operación), con aprobación, orden y confirmación.',
  p:[['Revisa el cálculo del mes','El prorrateo sale solo del mantenedor de Parques y las otorgadas.'],['Aprueba','Quien tiene el permiso valida el monto del parque.'],['Emite la orden y confirma el pago','Cada paso con su responsable.']],
  n:'El seguimiento por parque y sus cartolas están en sus propias páginas de Post Venta.' },
{ r:'/postventa/seguimiento-parques/', t:'Seguimiento Comisión Parques', i:'bi-p-square', d:'El estado del circuito de parques mes a mes: qué parque está calculado, aprobado, con orden o pagado.',
  p:[['Sigue el tablero','Cada parque muestra su paso actual del circuito.']],
  n:'Las cartolas del parque se emiten en Emisión de Cartolas Parque.' },
{ r:'/postventa/cartolas-parque/', t:'Emisión de Cartolas Parque', i:'bi-envelope-paper', d:'La cartola del parque: el detalle de operaciones y montos que respalda el pago del mes, para enviar al parque.',
  p:[['Genera la cartola del mes','Con el circuito aprobado, la cartola sale con el detalle.'],['Envía','Queda registrado qué se envió y cuándo.']],
  n:'La cartola es el respaldo del pago: lo que se paga es lo que la cartola dice.' },
{ r:'/postventa/facturacion-af/', t:'Facturación AutoFácil', i:'bi-receipt-cutoff', d:'Cuadra lo facturado contra lo pagado por financiera y concepto (colocación, seguros, UAC): detecta diferencias operación por operación.',
  p:[['Elige mes y financiera','Cada bloque muestra sus operaciones con lo esperado vs lo facturado.'],['Revisa las diferencias','Dif $ y Dif % marcan dónde no cuadra.'],['Exporta','Cada detalle baja a Excel con un clic.']],
  n:'Una diferencia persistente es una conversación con la financiera, no un ajuste silencioso.' },
{ r:'/postventa/vendedores-ventas/', t:'Vendedores con Ventas', i:'bi-person-badge', d:'Ranking de vendedores del dealer y su detalle mensual. El vendedor sale de la CARTA de aprobación, no del crédito.',
  p:[['Elige el mes','El ranking muestra ventas por vendedor y dealer.'],['Abre el detalle','Las operaciones que componen cada cifra.']],
  n:'Si un vendedor no aparece, revisa que la carta lo tenga registrado.' },

/* ═══ COMISIONES INTERNAS ═══ */
{ r:'/comisiones/revision/', t:'Revisión y Aprobación de Comisiones', i:'bi-clipboard-check', d:'La liquidación mensual de cada ejecutivo: piso, incentivo por cumplimiento y ajustes, operación por operación, con flujo de revisión y aprobación.',
  p:[['Elige mes y ejecutivo','Solo ves los ejecutivos que tienes asignados.'],['Revisa el detalle','Cada operación con su aporte al cálculo; los ajustes manuales quedan registrados.'],['Aprueba','Las comisiones no aprobadas a tiempo las aprueba solo el motor automático.']],
  n:'Las variables del cálculo (tramos, pisos, factores) viven en el Mantenedor de Variables.' },
{ r:'/comisiones/variables/', t:'Variables de Comisiones', i:'bi-sliders2', d:'Los parámetros del cálculo de comisiones de ejecutivos: tramos de cumplimiento, pisos, factores e incentivos. Todo paramétrico, nada en código.',
  p:[['Edita la variable','El cambio aplica al próximo cálculo, no reescribe lo ya aprobado.']],
  n:'Tras un cambio, verifica un ejecutivo de muestra en Revisión antes del cierre.' },
{ r:'/comisiones/bono-jefe/', t:'Bono Jefe Comercial', i:'bi-trophy', d:'El bono del Jefe Comercial: un BSC con metas ponderadas, topes y curva exponencial de cumplimiento.',
  p:[['Revisa el período','Cada meta muestra su cumplimiento y aporte al bono.'],['Ajusta variables (con permiso)','Ponderaciones y topes son paramétricos.']],
  n:'El resultado alimenta la liquidación del período como las demás comisiones.' },

/* ═══ DEALERS ═══ */
{ r:'/dealers-incorporacion/parques.html/', t:'Creación de Parque', i:'bi-p-circle', d:'La ficha de incorporación de un PARQUE por la misma máquina de dealers: datos, arriendo pactado y cadena de aprobación.',
  p:[['Llena la ficha del parque','Entidad PARQUE: sus términos son arriendo mensual, no comisión por operación.'],['Envía a autorización','Recorre los mismos niveles paramétricos que un dealer.']],
  n:'El arriendo pactado alimenta el prorrateo mensual de Comisiones Parques.' },
{ r:'/dealers-liquidez/', t:'Plan Liquidez', i:'bi-droplet', d:'Anticipo de comisiones para dealers Super Partner: una hoja de liquidez con aprobación en tres niveles (Jefe/Gerente Comercial → Gerente General → conocimiento de Finanzas).',
  p:[['Genera la hoja','Selecciona el dealer y las comisiones a anticipar.'],['Recorre las firmas','Cada nivel aprueba en orden; Finanzas toma conocimiento al final.']],
  n:'El anticipo se descuenta de la cartola siguiente del dealer.' },
{ r:'/dealernet-informes/', t:'Informes DealerNet', i:'bi-clipboard-data', d:'La integración con DealerNet: consulta el comportamiento externo de un RUT, guarda el informe en el repositorio y controla el costo por consulta.',
  p:[['Consulta por RUT','El informe llega y queda guardado: la misma consulta no se paga dos veces.'],['Revisa el repositorio','Todos los informes traídos, con su resumen IA.'],['Controla el gasto','Auditoría de uso y facturación interna por consulta.']],
  n:'La Evaluación Crediticia consulta DealerNet sola cuando arma la ficha.' },
{ r:'/informes-dealernet/', t:'Informes DealerNet (Clientes)', i:'bi-clipboard-data', d:'El repositorio de informes DealerNet ya consultados, buscable por cliente.',
  p:[['Busca por RUT','Si el informe existe, lo ves sin pagar una consulta nueva.']],
  n:'Para traer un informe nuevo usa la consulta de Informes DealerNet.' },

/* ═══ CONTABILIDAD ═══ */
{ r:'/contabilidad/', t:'Contabilidad', i:'bi-calculator-fill', d:'La contabilidad completa del negocio, construida SOLA desde la operación: cada movimiento de dinero genera su asiento por el motor de centralización. El reemplazo de AVSOFT.',
  p:[['Revisa el Guardián','Es la lista de pendientes: eventos sin regla o descuadrados.'],['Consulta libros y balance','Diario, Mayor, Balance y Estados Financieros salen de los comprobantes.'],['Cablea reglas nuevas','Todo evento nuevo de negocio necesita su Regla de Centralización.']],
  s:[['Plan de Cuentas / Comprobantes / Libros','La base contable clásica.'],['Reglas de Centralización','Qué asiento genera cada evento del negocio.'],['Guardián Contable','Lo que quedó sin contabilizar: la cola de trabajo.'],['F29 / LRE / Libros Auxiliares','Las salidas tributarias.']],
  n:'La contabilidad nunca bloquea la operación: si algo falla, queda en el log del Guardián para arreglarlo.' },
{ r:'/contabilidad/plan-cuentas/', t:'Plan de Cuentas', i:'bi-diagram-2', d:'El árbol de cuentas contables: código, nombre, naturaleza y jerarquía. Las cuentas nunca llevan año: la separación por ejercicio la da el período.',
  p:[['Busca o crea la cuenta','Respeta la jerarquía y la naturaleza (activo, pasivo, resultado).']],
  n:'Antes de crear una cuenta, revisa si la regla de centralización puede usar una existente.' },
{ r:'/contabilidad/comprobantes/', t:'Comprobantes', i:'bi-journal-plus', d:'Los comprobantes contables: los automáticos que genera el motor y los manuales de ajuste, cada uno con sus líneas cuadradas.',
  p:[['Consulta por período o tipo','Cada comprobante muestra su origen (evento de negocio o manual).'],['Digita el manual solo si no hay regla','Un asiento manual recurrente es una regla de centralización que falta.']],
  n:'Los meses cerrados no aceptan comprobantes nuevos.' },
{ r:'/contabilidad/libros/', t:'Libros Diario y Mayor', i:'bi-book', d:'El Libro Diario (cronológico) y el Mayor (por cuenta) del período, incluida la historia importada de AVSOFT.',
  p:[['Elige libro y período','Exportable para revisión o fiscalización.']], n:null },
{ r:'/contabilidad/balance/', t:'Balance de Comprobación', i:'bi-clipboard-data', d:'El balance de sumas y saldos: la foto de todas las cuentas del período, para verificar que todo cuadra.',
  p:[['Genera por período','Débitos = créditos siempre; si no, hay un comprobante descuadrado que el Guardián debe acusar.']], n:null },
{ r:'/contabilidad/reglas/', t:'Reglas de Centralización', i:'bi-diagram-3', d:'El mantenedor que cablea cada evento del negocio a su asiento: qué cuentas se cargan y abonan cuando pasa cada cosa (pago, devengo, comisión, provisión).',
  p:[['Revisa la regla del evento','Cada regla dice sus cuentas de cargo/abono y el tratamiento de impuestos.'],['Crea la que falta','Si el Guardián acusa SIN_REGLA, ese evento necesita su regla aquí.']],
  n:'Regla nueva o editada: verifica con el siguiente evento real que el asiento salga cuadrado.' },
{ r:'/contabilidad/estados/', t:'Estados Financieros', i:'bi-graph-up', d:'Balance General y Estado de Resultados armados desde los comprobantes del período.',
  p:[['Elige el período','Compara contra meses anteriores y contra el presupuesto.']], n:null },
{ r:'/contabilidad/cierre-mes/', t:'Informe Cierre Mensual (Contable)', i:'bi-journal-check', d:'El informe contable del mes cerrado: estados, cuadraturas y notas para el grupo.',
  p:[['Genera con el mes cerrado','Los números salen congelados por el candado del cierre.']], n:null },
{ r:'/contabilidad/bitacora-cierres/', t:'Bitácora de Cierres', i:'bi-clock-history', d:'La historia de los cierres contables: quién cerró cada período, cuándo, y las reaperturas con su motivo.',
  p:[['Consulta el historial','Solo lectura; las reaperturas son excepción documentada.']], n:null },
{ r:'/contabilidad/guardian/', t:'Guardián Contable', i:'bi-shield-exclamation', d:'La lista de pendientes de la contabilidad automática: eventos que quedaron SIN_REGLA, DESCUADRE o ERROR. Si esta lista está vacía, la contabilidad se está construyendo sola.',
  p:[['Revisa cada pendiente','El evento dice qué pasó y por qué no se contabilizó.'],['Cablea o corrige','SIN_REGLA → crear la regla; DESCUADRE → revisar montos del evento.']],
  n:'Un pendiente viejo es un asiento que falta en los libros: no dejar envejecer.' },
{ r:'/contabilidad/punto-restauracion/', t:'Punto de Restauración (Contabilidad)', i:'bi-clock-history', d:'Marca un punto en el tiempo de la contabilidad y permite volver a él si una carga o proceso salió mal. Herramienta de administrador, usar con criterio.',
  p:[['Crea la marca ANTES del proceso riesgoso','Importación masiva, recableado de reglas.'],['Restaura solo si es necesario','Borra lo posterior a la marca: es irreversible.']],
  n:'No reemplaza al respaldo de BD: es un deshacer quirúrgico de contabilidad.' },
{ r:'/contabilidad/directorio/', t:'Presentación Directorio', i:'bi-easel2', d:'La presentación financiera para el directorio: los estados y KPIs del período en formato lámina.',
  p:[['Elige el período','Las láminas se arman con los datos contables reales.']], n:null },
{ r:'/contabilidad/libros-auxiliares/', t:'Libros Auxiliares', i:'bi-journals', d:'Los auxiliares por cuenta: el detalle documento a documento detrás de cada saldo (proveedores, clientes, bancos).',
  p:[['Elige cuenta y período','Cada línea con su documento de origen.']], n:null },
{ r:'/contabilidad/f29/', t:'F29 Borrador', i:'bi-file-earmark-ruled', d:'El borrador del F29 armado desde el sistema: IVA débito y crédito, retenciones y PPM salen de los asientos del período, no de una planilla aparte.',
  p:[['Genera el borrador del mes','Compara contra el RCV del SII antes de declarar.']],
  n:'Diferencias contra el RCV suelen ser documentos sin registrar: revisa el libro de compras.' },
{ r:'/contabilidad/lre/', t:'LRE — Libro Remuneraciones Electrónico', i:'bi-people', d:'El Libro de Remuneraciones Electrónico para la DT, armado desde las remuneraciones de RRHH.',
  p:[['Genera el período','Valida contra las liquidaciones antes de subir a la DT.']], n:null },
{ r:'/contabilidad/presupuesto/', t:'Presupuesto Anual', i:'bi-clipboard-data', d:'El presupuesto anual por cuenta y su seguimiento: lo real del mes contra lo presupuestado, con desviaciones.',
  p:[['Carga o edita el presupuesto','Por cuenta y mes.'],['Sigue la ejecución','Las desviaciones grandes merecen nota.']], n:null },
{ r:'/contabilidad/finanzas-ia/', t:'Pregúntale a Finanzas', i:'bi-chat-dots', d:'Consulta en lenguaje natural sobre los datos contables: gastos, tendencias y composiciones respondidas desde los comprobantes reales.',
  p:[['Pregunta como hablas','Ej: "¿cuánto gastamos en arriendos este año?".']],
  n:'Para el número oficial, confirma en Libros o Balance.' },
{ r:'/contabilidad/cluster-pg/', t:'Cluster Balance PG', i:'bi-collection', d:'Agrupación del balance en clusters de presentación (estilo P&G gerencial): las cuentas se mapean a líneas de lectura ejecutiva.',
  p:[['Revisa el mapeo','Cada cuenta pertenece a un cluster; una cuenta sin cluster no aparece en la lectura gerencial.']], n:null },

/* ═══ RRHH ═══ */
{ r:'/recursos-humanos/', t:'Recursos Humanos', i:'bi-people-fill', d:'La suite de personas: ficha y carpeta del colaborador, vacaciones, ausencias, remuneraciones, contratos, desempeño, clima y compliance.',
  p:[['Parte por Colaboradores','La fuente única de datos del personal.'],['Gestiona el ciclo','Vacaciones y ausencias con devengo automático; remuneraciones validadas al peso.'],['Cuida el clima','Encuestas, desempeño y el Canal de Compliance.']],
  s:[['Colaboradores / Mi Ficha','Datos, carpeta y documentos de cada persona.'],['Vacaciones / Ausencias / Asistencia','El control de tiempo, con reloj Workera.'],['Remuneraciones / Contratos','El ciclo salarial completo.'],['Compliance','Denuncias protegidas (Ley Karin), anónimas con código.']],
  n:'El LRE para la DT y las provisiones de vacaciones salen solos hacia Contabilidad.' },
{ r:'/recursos-humanos/colaboradores/', t:'Colaboradores', i:'bi-people', d:'La ficha maestra de cada colaborador: datos, cargo, jefatura, renta y su carpeta de documentos. Fuente única del personal.',
  p:[['Busca o crea al colaborador','Todo lo demás de RRHH cuelga de esta ficha.'],['Mantén la carpeta','Contratos, anexos y certificados en un solo lugar.']],
  n:'Un dato malo aquí se propaga a remuneraciones, contratos y credenciales: es LA fuente.' },
{ r:'/recursos-humanos/mi-ficha/', t:'Mi Ficha', i:'bi-person-vcard', d:'Tu ficha personal: tus datos, tu carpeta, tus vacaciones disponibles y tus documentos firmados.',
  p:[['Revisa tus datos','Si algo está mal, solicita la corrección a RRHH.'],['Descarga tus documentos','Liquidaciones, contratos y certificados.']], n:null },
{ r:'/recursos-humanos/vacaciones/', t:'Solicitudes de Vacaciones', i:'bi-sun', d:'Pide tus vacaciones y sigue su aprobación. El saldo se devenga automáticamente mes a mes.',
  p:[['Solicita el período','El sistema muestra tu saldo disponible real.'],['Espera la aprobación','Tu jefatura aprueba; el descuento del saldo es automático.']],
  n:'El devengo y la provisión contable corren solos: tu saldo siempre está al día.' },
{ r:'/recursos-humanos/ausencias/', t:'Ausencias y Permisos', i:'bi-calendar-x', d:'Registro de licencias, permisos y ausencias con su respaldo documental.',
  p:[['Registra la ausencia','Tipo, fechas y documento (licencia, comprobante).']],
  n:'Las ausencias alimentan remuneraciones y los indicadores de RRHH.' },
{ r:'/recursos-humanos/asistencia/', t:'Asistencia (Workera)', i:'bi-fingerprint', d:'La asistencia del reloj control Workera sincronizada al sistema: marcas, atrasos e inasistencias.',
  p:[['Revisa las marcas','Por persona y período; las diferencias se gestionan con RRHH.']],
  n:'La Jornada Laboral define contra qué horario se compara cada marca.' },
{ r:'/recursos-humanos/jornada/', t:'Jornada Laboral', i:'bi-clock', d:'Los horarios de trabajo por persona o equipo: contra esto se comparan las marcas de asistencia.',
  p:[['Define la jornada','Días, horas de entrada/salida y colación.']], n:null },
{ r:'/recursos-humanos/remuneraciones/', t:'Remuneraciones', i:'bi-cash-stack', d:'El proceso mensual de remuneraciones: haberes, descuentos y liquidaciones, validado al peso contra el sistema anterior.',
  p:[['Procesa el mes','Con indicadores actualizados (Mantenedores → Indicadores de Remuneraciones).'],['Revisa las liquidaciones','Antes de cerrar, valida los casos con cambios del mes.']],
  n:'El LRE y la contabilización salen de este proceso.' },
{ r:'/recursos-humanos/aumento-renta/', t:'Aumento de Renta', i:'bi-graph-up-arrow', d:'Solicitudes de aumento de renta con su flujo de aprobación y efecto en el contrato.',
  p:[['Genera la solicitud','Monto propuesto y justificación.'],['Aprueba por nivel','Aprobada, genera el anexo y actualiza la renta.']], n:null },
{ r:'/recursos-humanos/contratos/', t:'Contratos y Cartas Oferta', i:'bi-file-earmark-text', d:'Generación de contratos, anexos y cartas oferta desde plantillas, con los datos de la ficha.',
  p:[['Elige plantilla y colaborador','El documento se arma con los datos reales.'],['Genera y archiva','El firmado queda en la carpeta del colaborador.']], n:null },
{ r:'/recursos-humanos/antiguedad/', t:'Certificado de Antigüedad', i:'bi-award', d:'Emisión del certificado de antigüedad laboral, verificable con QR.',
  p:[['Emítelo','Sale con los datos de la ficha y su código de verificación.']], n:null },
{ r:'/recursos-humanos/desempeno/', t:'Evaluaciones de Desempeño', i:'bi-clipboard-check', d:'El ciclo de evaluaciones: pautas, evaluadores y resultados por período.',
  p:[['Configura el ciclo','Pauta y evaluadores por persona.'],['Evalúa y cierra','Los resultados quedan en la ficha para desarrollo y renta.']], n:null },
{ r:'/recursos-humanos/cursos/', t:'Cursos y Capacitaciones', i:'bi-mortarboard', d:'Registro de capacitaciones: quién hizo qué curso, cuándo y con qué resultado.',
  p:[['Registra el curso','Interno o externo, con certificado si existe.']],
  n:'Los cursos internos de la plataforma viven en Academia AutoFácil.' },
{ r:'/recursos-humanos/encuestas/', t:'Encuestas de Clima', i:'bi-emoji-smile', d:'Encuestas de clima organizacional: diseño, aplicación anónima y resultados.',
  p:[['Lanza la encuesta','Las respuestas son anónimas.'],['Lee los resultados','Por dimensión y evolución en el tiempo.']], n:null },
{ r:'/recursos-humanos/compliance/', t:'Canal de Compliance', i:'bi-shield-lock', d:'El canal de denuncias (Ley Karin): denuncias protegidas, anónimas si se desea, con código de seguimiento para el denunciante.',
  p:[['Recibe y gestiona','Solo quienes tienen el permiso de gestión ven las denuncias.'],['Documenta cada paso','La investigación queda trazada; el denunciante consulta avance con su código.']],
  n:'La confidencialidad es la regla: el acceso está restringido por permiso específico.' },
{ r:'/recursos-humanos/solicitudes/', t:'Solicitudes RRHH', i:'bi-inbox', d:'La bandeja de solicitudes del personal: certificados, correcciones de datos y otros requerimientos.',
  p:[['Gestiona la cola','Cada solicitud con su estado y responsable.']], n:null },
{ r:'/recursos-humanos/documentos-firmados/', t:'Documentos Firmados', i:'bi-file-earmark-check', d:'El repositorio de documentos firmados por los colaboradores: contratos, anexos, reglamentos y políticas.',
  p:[['Consulta por persona o documento','Quién firmó qué y cuándo.']], n:null },
{ r:'/recursos-humanos/analytics/', t:'Indicadores RRHH', i:'bi-bar-chart-line', d:'Los KPIs de personas: dotación, rotación, ausentismo, antigüedad y su evolución.',
  p:[['Elige el corte','Por área, período o indicador.']], n:null },
{ r:'/recursos-humanos/directorio/', t:'Directorio', i:'bi-person-lines-fill', d:'El directorio del equipo: quién es quién, su cargo, área y contacto.',
  p:[['Busca a la persona','Con su anexo, correo y ubicación en el organigrama.']], n:null },
{ r:'/recursos-humanos/concurso/', t:'¿Qué Dice AutoFácil?', i:'bi-controller', d:'El concurso interno estilo programa de TV: preguntas sobre la operación real, por equipos.',
  p:[['Juega','Responde con tu equipo; el ranking es en vivo.']],
  n:'Las preguntas se editan con el permiso de concurso.' },
{ r:'/recursos-humanos/kuder/', t:'Test de Kuder', i:'bi-compass', d:'El test vocacional de intereses: apoya conversaciones de desarrollo interno.',
  p:[['Responde el test','Los resultados por área de interés quedan en tu ficha.']], n:null },

/* ═══ SOPORTE ═══ */
{ r:'/soporte/', t:'Soporte', i:'bi-headset', d:'Los servicios internos: compras de oficina con aprobación por niveles, tickets a TI, avisos oficiales y apps móviles.',
  p:[['Pide lo que necesitas','Compras para insumos; Tickets para problemas técnicos.']],
  s:[['Compras de Oficina','Solicitud → aprobación por niveles → orden de compra.'],['Reportar a TI','Mesa de ayuda con SLA y escalamiento.'],['Avisos en Línea','Comunicados oficiales de la empresa.'],['Aplicaciones Móviles','Las PWA instalables de la suite.']],
  n:'Una compra aprobada termina como Orden de Pago al proveedor.' },
{ r:'/soporte/compras/', t:'Compras de Oficina', i:'bi-bag', d:'Solicita compras de insumos y servicios: la solicitud recorre la cadena de aprobación configurada según monto.',
  p:[['Crea la solicitud','Qué necesitas, cantidad y justificación.'],['Sigue la aprobación','Cada nivel aprueba según el mantenedor de Compras.']],
  n:'Aprobada, pasa a orden de compra y luego a ODP.' },
{ r:'/soporte/compras-admin/', t:'Administrar Compras', i:'bi-bag-check', d:'La gestión del circuito de compras: aprobar solicitudes, generar órdenes y controlar el gasto.',
  p:[['Aprueba tu nivel','Las solicitudes pendientes de tu firma.'],['Genera la orden','Con la cadena completa, la orden va al proveedor.']], n:null },
{ r:'/soporte/compras-revision/', t:'Revisión de Órdenes de Compra', i:'bi-clipboard-check', d:'La revisión final de órdenes emitidas: conformidad de lo recibido antes de liberar el pago.',
  p:[['Revisa la orden contra lo recibido','La conformidad libera la ODP.']], n:null },
{ r:'/soporte/tickets-ti/', t:'Reportar a TI (Tickets)', i:'bi-life-preserver', d:'La mesa de ayuda: reporta problemas técnicos con motivo tipificado, SLA y escalamiento automático si no se atiende a tiempo.',
  p:[['Crea el ticket','Motivo, descripción y pantallazo si ayuda.'],['Sigue el estado','El SLA corre solo; si vence, escala a jefatura.']],
  n:'Motivos, SLA y escalamiento se configuran en Mantenedores → Tickets TI.' },
{ r:'/soporte/apps-moviles/', t:'Aplicaciones Móviles', i:'bi-phone', d:'Las PWA instalables de la suite (Terreno, ¿Dónde Curso? y más): qué hace cada una y cómo instalarla en el teléfono.',
  p:[['Elige la app','Sigue las instrucciones de instalación de tu sistema (Android/iPhone).']], n:null },
{ r:'/soporte/avisos/', t:'Avisos en Línea', i:'bi-megaphone', d:'Los comunicados oficiales de la empresa: publicación y acuse de lectura.',
  p:[['Lee y confirma','Los avisos con acuse requieren tu confirmación de lectura.']], n:null },

/* ═══ MANTENEDORES ═══ */
{ r:'/mantenedores/tasas/', t:'Tasas de Interés', i:'bi-percent', d:'Las tasas vigentes por tramo y producto. Todo cálculo de cuota y rentabilidad lee de aquí: una tasa mal cargada afecta cada cotización.',
  p:[['Revisa la vigencia','Cada tasa con su período de validez.'],['Carga la nueva','La anterior queda como historia; los créditos otorgados no cambian.']],
  n:'El footer de la página lista qué procesos afecta cada tasa.' },
{ r:'/mantenedores/uf/', t:'Valores UF', i:'bi-currency-dollar', d:'La serie histórica de la UF, sincronizada desde la CMF. Clasificaciones (mayor/menor 200 UF) y cálculos la leen de aquí.',
  p:[['Verifica la sincronización','Los valores llegan solos; revisa que no haya huecos de fechas.']],
  n:'Un hueco en la serie rompe cálculos por fecha: repórtalo si lo ves.' },
{ r:'/mantenedores/impuestos/', t:'Impuestos', i:'bi-percent', d:'IVA y retenciones vigentes: el motor de asientos y las comisiones los leen de aquí para desagregar bruto/neto.',
  p:[['Actualiza solo con cambio legal','El cambio aplica desde su vigencia, no hacia atrás.']],
  n:'Las comisiones dealer son SIEMPRE brutas (IVA incluido); la desagregación usa estos valores.' },
{ r:'/mantenedores/parametros/', t:'Parámetros Crédito', i:'bi-sliders', d:'Los parámetros del producto: gastos, umbrales, factores del cálculo de crédito y rentabilidad.',
  p:[['Edita el parámetro','El footer indica qué páginas y procesos afecta cada uno.']],
  n:'Cambio sensible: valida con una cotización de prueba antes de avisar al equipo.' },
{ r:'/mantenedores/factores-seguro/', t:'Factores de Seguros Clientes', i:'bi-shield-check', d:'Los factores por tramo de los seguros del cliente (desgravamen, RDH, cesantía) que componen la cuota.',
  p:[['Actualiza el factor','Aplica a cotizaciones nuevas; lo otorgado no cambia.']], n:null },
{ r:'/mantenedores/comisiones-seguro/', t:'Comisiones de Seguro', i:'bi-umbrella', d:'Las comisiones que la compañía paga por los seguros intermediados: alimentan rentabilidad y penetración.',
  p:[['Revisa por producto','Cada seguro con su comisión vigente.']], n:null },
{ r:'/mantenedores/financieras/', t:'Fórmulas Comisiones Financieras', i:'bi-calculator', d:'Cómo paga cada financiera: las fórmulas de ingreso por colocación y seguros de AutoFin y los tiers de Unidad de Crédito.',
  p:[['Edita la fórmula','Rentabilidad, simuladores y ¿Dónde Curso? leen de aquí.']],
  n:'Tras un cambio, valida una operación de muestra en el Simulador de Rentabilidad.' },
{ r:'/mantenedores/productos-financiera/', t:'Productos Financiera', i:'bi-tags-fill', d:'El catálogo de productos por financiera y su mapeo con los códigos que llegan en las cargas.',
  p:[['Mantén el mapeo','Un producto sin mapear queda mal clasificado en las cargas.']], n:null },
{ r:'/mantenedores/preferencia-financiera/', t:'Preferencia Financiera', i:'bi-signpost-split', d:'La grilla cuotas×saldo de elegibilidad: qué financiera puede tomar cada combinación. Es la regla de ELEGIBILIDAD de ¿Dónde Curso? (la rentabilidad la pone el calculador).',
  p:[['Edita la celda','Marca qué financiera acepta ese tramo de cuotas y saldo.']],
  n:'El informe Rentabilidad Créditos audita el resultado real contra el calculador.' },
{ r:'/mantenedores/dealers/', t:'Dealers', i:'bi-building', d:'La base de dealers vigentes: datos, banco y su tabla de comisiones propia — la que RIGE sus operaciones (la pizarra es solo el default).',
  p:[['Busca el dealer','Edita datos generales con el permiso correspondiente.'],['Respeta el circuito','Altas y cambios de términos van por Dealers Incorporación, no por edición directa.']],
  n:'La comisión pactada del dealer es la fuente única que leen cartas y créditos.' },
{ r:'/mantenedores/dealer-categorias/', t:'Categorías de Dealers', i:'bi-award', d:'Las categorías (Partner, Super Partner…) y sus beneficios: clasifican a cada dealer y habilitan cosas como el Plan Liquidez.',
  p:[['Define la categoría','Nombre, criterios y beneficios.']], n:null },
{ r:'/mantenedores/parques/', t:'Arriendos y Comisiones Parque y Calle', i:'bi-p-circle', d:'La pizarra por defecto: arriendos de parques y comisiones de calle. Precarga las fichas de dealer y define el umbral de "participación especial".',
  p:[['Edita la pizarra','Lo que supere estos valores en una ficha escala a Gerencia.']],
  n:'El arriendo del parque se prorratea entre las otorgadas del mes: nunca fee por operación.' },
{ r:'/mantenedores/vehiculos/', t:'Mantenedor Vehículos', i:'bi-car-front', d:'El catálogo de marcas y modelos que usan cotizaciones y créditos.',
  p:[['Agrega o corrige','Marca, modelo y estado (activo/inactivo).']], n:null },
{ r:'/mantenedores/comunas/', t:'Comunas', i:'bi-geo-alt', d:'El catálogo de comunas y regiones que usan las direcciones de todo el sistema.',
  p:[['Manténlo homologado','Una comuna duplicada o mal escrita ensucia todas las direcciones.']], n:null },
{ r:'/mantenedores/actividades-economicas/', t:'Actividades Económicas', i:'bi-briefcase', d:'Los códigos de actividad económica del SII (674 códigos) para clasificar giros de clientes y proveedores.',
  p:[['Busca el código','Por texto o número de actividad.']], n:null },
{ r:'/mantenedores/tipos-documento/', t:'Tipos de Documento', i:'bi-paperclip', d:'Los tipos de documento que el sistema exige y almacena (cédula, liquidación, pagaré…): qué es obligatorio en cada proceso.',
  p:[['Define el tipo','Nombre, proceso al que aplica y obligatoriedad.']], n:null },
{ r:'/mantenedores/pagares/', t:'Pagarés AutoFácil', i:'bi-file-earmark-text', d:'Las plantillas del pagaré: el texto legal que se imprime con los datos de cada operación.',
  p:[['Edita con respaldo legal','Un cambio de texto aplica a los pagarés que se impriman desde entonces.']], n:null },
{ r:'/mantenedores/certificados-textos/', t:'Textos de Certificados', i:'bi-file-earmark-text', d:'Los textos paramétricos de cada certificado emitible: encabezados, cuerpos y pies.',
  p:[['Edita la plantilla','El certificado sale con este texto y los datos reales del crédito.']], n:null },
{ r:'/mantenedores/cuentas-bancarias/', t:'Cuentas Bancarias', i:'bi-bank', d:'Las cuentas bancarias de la empresa: las que usan tesorería, conciliación y los pagos.',
  p:[['Registra la cuenta','Banco, número y uso. Los módulos la referencian, nunca la copian.']], n:null },
{ r:'/mantenedores/estado-creditos/', t:'Etapas y Estados', i:'bi-diagram-3-fill', d:'La máquina de estados paramétrica: las etapas del crédito, sus transiciones permitidas y el flujo Brokerage dibujado. Hoy configura y documenta; el bloqueo duro se activará cuando el mapa esté validado.',
  p:[['Revisa el mapa','Estados iniciales, finales y transiciones por ámbito.'],['Edita con criterio','Cambiar el mapa cambia lo que el sistema considerará válido.']],
  n:'La segunda dimensión (Estado Cartera) vive en esta misma página.' },
{ r:'/mantenedores/meses-cerrados/', t:'Meses Cerrados', i:'bi-lock', d:'El candado por período: un mes cerrado no acepta ediciones en créditos, comisiones ni contabilidad.',
  p:[['Consulta el estado','Qué meses están cerrados y por quién.'],['Reabre solo por excepción','Queda auditado; ciérralo apenas termine la corrección.']],
  n:'El cierre formal con checklist se hace en Tesorería → Cierre de Mes.' },
{ r:'/mantenedores/recalculo-programado/', t:'Recálculo Programado', i:'bi-arrow-repeat', d:'El recálculo nocturno de comisiones y campos derivados: qué recalcula, cuándo y su última corrida. Respeta campos forzados y meses cerrados.',
  p:[['Revisa la última corrida','Qué operaciones tocó y si hubo errores.']],
  n:'Un valor pactado a mano debe estar FORZADO o el recálculo lo pisará.' },
{ r:'/mantenedores/bd-operaciones-edicion/', t:'BD Operaciones', i:'bi-database-gear', d:'Edición directa de la tabla de créditos, por niveles: Solo Dios edita todo; Analista solo meses abiertos. Cada cambio queda auditado.',
  p:[['Ubica el registro','Busca por N° OP.'],['Edita con criterio','Es cirugía directa a la base: para flujos normales usa Edición Créditos.']],
  n:'Si el valor editado es calculable, márcalo forzado o el recálculo lo revertirá.' },
{ r:'/mantenedores/bd-clientes-edicion/', t:'BD Clientes', i:'bi-database', d:'Edición directa de la tabla de clientes, por niveles y auditada.',
  p:[['Corrige el dato','Recuerda: clientes es fuente única — el cambio se refleja en todo el sistema.']], n:null },
{ r:'/mantenedores/bd-antecedentes-edicion/', t:'BD Antecedentes Laborales', i:'bi-briefcase-fill', d:'Edición directa de antecedentes laborales, por niveles y auditada.',
  p:[['Corrige el dato','Con respaldo del documento que lo justifica.']], n:null },
{ r:'/mantenedores/bd-informacion-comercial-edicion/', t:'BD Información Comercial', i:'bi-building-fill', d:'Edición directa de la información comercial, por niveles y auditada.',
  p:[['Corrige el dato','Con su origen documentado.']], n:null },
{ r:'/mantenedores/broker-validaciones/', t:'Documentos a Validar Brokers', i:'bi-card-checklist', d:'El checklist paramétrico de documentos que se valida a los créditos broker.',
  p:[['Define el checklist','Qué documento se exige y en qué paso.']], n:null },
{ r:'/mantenedores/solo-dios/', t:'SOLO DIOS', i:'bi-lightning-charge-fill', d:'Las herramientas extremas del administrador: acceso total a las bases y la Consola SQL de solo lectura auditada. Máximo poder, máximo registro.',
  p:[['Úsalo como último recurso','Todo lo que hagas queda auditado con tu nombre.']],
  n:'Si lo que necesitas existe como mantenedor normal, usa el mantenedor.' },
{ r:'/mantenedores/punto-restauracion/', t:'Punto de Restauración (UAT)', i:'bi-clock-history', d:'Marca el estado de créditos y sus tablas hijas, y permite borrar todo lo POSTERIOR a la marca. Para pruebas UAT, no para producción diaria.',
  p:[['Marca antes de probar','Crea el punto antes de la carga o prueba masiva.'],['Restaura si algo salió mal','Borra lo posterior a la marca: irreversible.']],
  n:'Es una herramienta Solo Dios: doble verificación antes de restaurar.' },
{ r:'/mantenedores/vista-pantallas/', t:'Vista Pantallas', i:'bi-layout-wtf', d:'Mueve cards entre secciones del home y las landings sin tocar código: dónde aparece cada acceso.',
  p:[['Arrastra la card a su sección','El cambio aplica para todos al recargar.']],
  n:'La visibilidad (quién la ve) NO se define aquí: eso es Perfiles y Permisos.' },
{ r:'/mantenedores/presupuesto/', t:'Presupuesto', i:'bi-clipboard-data', d:'La meta mensual de colocación (operaciones y monto) que usa el Dashboard para medir cumplimiento.',
  p:[['Carga la meta del mes','El Dashboard compara lo real contra esto.']], n:null },
{ r:'/mantenedores/feriados/', t:'Feriados', i:'bi-calendar-event', d:'El calendario de feriados: los plazos en horas hábiles (workflows, SLA) lo usan para no contar días festivos.',
  p:[['Mantén el año al día','Un feriado no cargado hace vencer SLA en días festivos.']], n:null },
{ r:'/mantenedores/horarios-analistas/', t:'Horarios Analistas de Crédito', i:'bi-alarm', d:'Los turnos de los analistas: contra esto se miden la asignación del pool y los tiempos de respuesta.',
  p:[['Define el turno','Días y horarios por analista.']], n:null },
{ r:'/mantenedores/workflows/', t:'Workflows y Escalamiento', i:'bi-diagram-3-fill', d:'Los 15 flujos de aprobación del sistema: quién participa en cada paso, plazos en horas hábiles y a quién escala si no se atiende.',
  p:[['Elige el flujo','Cada paso muestra sus responsables y plazo.'],['Ajusta con cuidado','Cambiar un flujo cambia quién puede aprobar qué desde ese momento.']],
  n:'El log del workflow muestra cada ejecución real con sus tiempos.' },
{ r:'/mantenedores/alertas/', t:'Alertas', i:'bi-bell-fill', d:'Las alertas automáticas del sistema: qué condición dispara cada aviso y a quién le llega.',
  p:[['Configura la alerta','Condición, destinatarios y canal.']],
  n:'La campanita personal se administra en Avisos; esto es la definición de las alertas de negocio.' },
{ r:'/mantenedores/avisos/', t:'Avisos (campanita)', i:'bi-bell', d:'El motor de la campanita: qué avisos existen, a quién le aparecen y cuándo se retiran solos.',
  p:[['Revisa las reglas de retiro','Un aviso que no se calla suele tener rota su clave de retiro.']],
  n:'Cada paso de un flujo debe retirar el aviso del paso anterior.' },
{ r:'/mantenedores/alertas-saldos/', t:'Alertas Saldos Precio', i:'bi-bell', d:'Los umbrales de alerta de los saldos de precio: cuándo un saldo pendiente debe generar aviso.',
  p:[['Define el umbral','Días o montos que gatillan la alerta.']], n:null },
{ r:'/mantenedores/correos-programados/', t:'Correos Programados', i:'bi-envelope-at', d:'Los correos automáticos del sistema (Informe Diario de Ventas y otros): a quién, cuándo y con qué contenido.',
  p:[['Edita el programa','Destinatarios y horario de cada envío.']],
  n:'En staging los envíos al mundo están apagados por diseño.' },
{ r:'/mantenedores/respuestas-rapidas/', t:'Respuestas Rápidas del Chat', i:'bi-chat-quote', d:'Los textos precargados de Atención Remota: las respuestas frecuentes a un clic.',
  p:[['Crea o edita la respuesta','Título corto y texto completo.']], n:null },
{ r:'/mantenedores/cobranza-parametros/', t:'Parámetros Cobranza', i:'bi-cash-stack', d:'Los parámetros del motor de cobranza: gastos de cobranza por tramo, tasas de mora y umbrales. El footer lista qué afecta cada uno.',
  p:[['Edita el parámetro','Aplica a los cálculos desde su vigencia; lo devengado no cambia.']],
  n:'El interés de mora usa la TMC fija al otorgamiento: el modo es paramétrico.' },
{ r:'/mantenedores/cobranza-mora/', t:'Automatizaciones de Cobranza', i:'bi-envelope-heart', d:'Los envíos automáticos por tramo de mora (correo y WhatsApp) cumpliendo la Ley 21.320: qué mensaje, a qué días, por qué canal.',
  p:[['Configura el tramo','Días de mora, plantilla y canal.'],['Respeta los límites legales','Horarios y frecuencia según la ley están cableados.']],
  n:'Los envíos corren solos como motor de fondo: revisa el log de envíos.' },
{ r:'/mantenedores/cobranza-judicial/', t:'Cobranza Judicial (catálogos)', i:'bi-bank', d:'Los catálogos del módulo judicial: abogados, tribunales y estados procesales.',
  p:[['Mantén los catálogos','Los expedientes solo usan valores de aquí.']], n:null },
{ r:'/mantenedores/preaprobacion/', t:'Políticas de Preaprobación', i:'bi-patch-check', d:'Las reglas de la evaluación automática del Portal del Dealer: montos, condiciones y criterios de rechazo automático.',
  p:[['Edita la política','Cada consulta del portal se evalúa contra estas reglas.']],
  n:'El resultado de cada evaluación queda en el Repositorio de Preaprobaciones.' },
{ r:'/mantenedores/fundantes-tipos/', t:'Documentos Fundantes (tipos)', i:'bi-folder-check', d:'Qué documentos fundantes se exigen por tipo de operación: el checklist que sigue el módulo de Fundantes.',
  p:[['Define el tipo','Nombre y obligatoriedad por caso.']], n:null },
{ r:'/mantenedores/dealernet/', t:'Mantenedor DealerNet', i:'bi-cloud-arrow-down', d:'La configuración de la integración DealerNet: credenciales, endpoints y comportamiento de las consultas.',
  p:[['Revisa la conexión','El estado de la integración y sus últimos usos.']], n:null },
{ r:'/mantenedores/dealernet-productos/', t:'Productos DealerNet', i:'bi-cloud-arrow-down', d:'Los productos/consultas contratados a DealerNet y su disponibilidad.',
  p:[['Configura el producto','Qué consultas están habilitadas.']], n:null },
{ r:'/mantenedores/dealernet-costos/', t:'Costo DealerNet', i:'bi-cash-coin', d:'El costo por consulta DealerNet: alimenta la facturación interna y la auditoría de gasto.',
  p:[['Actualiza el costo','Con el valor del contrato vigente.']], n:null },
{ r:'/mantenedores/inteligencia-artificial/', t:'Inteligencia Artificial', i:'bi-robot', d:'La configuración del subsistema de IA: qué funciones la usan, con qué modelo y cuánto ha costado.',
  p:[['Revisa el consumo','El gasto por función se trackea en vivo.'],['Habilita o apaga funciones','Cada uso de IA es paramétrico.']], n:null },
{ r:'/mantenedores/apis/', t:'APIs', i:'bi-plug-fill', d:'Las API keys de la API pública: qué empresa tiene acceso, con qué clave y su uso.',
  p:[['Emite la key','Por empresa, revocable en cualquier momento.']],
  n:'El Simulador Rápido es el principal consumidor externo.' },
{ r:'/mantenedores/endpoints/', t:'Catálogo de Endpoints', i:'bi-hdd-network', d:'El inventario de los endpoints del sistema: qué existe, qué hace y qué permiso exige.',
  p:[['Busca el endpoint','Documentación viva para desarrollo y auditoría.']], n:null },
{ r:'/mantenedores/uptime/', t:'Salud y Uptime', i:'bi-activity', d:'El monitoreo de la plataforma: uptime por servicio, salud de la base, motores apagados y costos de infraestructura.',
  p:[['Revisa el semáforo','Cada servicio con su disponibilidad medida cada 5 minutos.']],
  n:'Si un motor aparece apagado sin razón, es un hallazgo: los 29 deben correr en producción.' },
{ r:'/mantenedores/backups/', t:'Backups del Sistema', i:'bi-people', d:'El estado de los respaldos: el dump nocturno (30 días de retención) y el respaldo de TiDB.',
  p:[['Verifica el último respaldo','Fecha y tamaño del dump más reciente.']],
  n:'Un respaldo no probado no es respaldo: la restauración está documentada en el runbook.' },
{ r:'/mantenedores/servidor-hora/', t:'Hora del Servidor', i:'bi-clock-history', d:'La hora del servidor vs la hora de Chile: verifica que los timestamps del sistema estén alineados.',
  p:[['Compara las horas','Un desfase aquí explica fechas corridas en los registros.']], n:null },
{ r:'/mantenedores/mi-dia/', t:'Panel Mi Día (config)', i:'bi-sunrise', d:'Qué widgets ve cada perfil en su página Mi Día.',
  p:[['Asigna widgets por perfil','Cada perfil parte su día con lo que le sirve.']], n:null },
{ r:'/mantenedores/dashboard-parametros/', t:'Parámetros del Dashboard', i:'bi-sliders', d:'La configuración del Dashboard: umbrales, colores y comportamiento de sus indicadores.',
  p:[['Ajusta el parámetro','El tablero lo toma al recargar.']], n:null },
{ r:'/mantenedores/ranking-ventas/', t:'Ranking de Colocaciones', i:'bi-trophy', d:'La configuración del ranking de colocaciones que se muestra en pantallas y Mi Día.',
  p:[['Define el período y criterio','Qué se rankea y cómo se ordena.']], n:null },
{ r:'/mantenedores/carrera/', t:'Carrera de Colocaciones', i:'bi-flag', d:'La "carrera" gamificada del equipo comercial: metas, hitos y visualización en pantallas.',
  p:[['Configura la carrera','Meta, período y participantes.']], n:null },
{ r:'/mantenedores/remuneraciones/', t:'Indicadores de Remuneraciones', i:'bi-percent', d:'Los indicadores previsionales del mes (AFP, salud, topes): los que usa el proceso de remuneraciones. Se proponen desde Previred con IA y un humano los aplica.',
  p:[['Revisa la propuesta del mes','La IA propone desde Previred; tú validas y aplicas.']],
  n:'Sin indicadores del mes aplicados, remuneraciones no debe procesarse.' },
{ r:'/mantenedores/rrhh-saludos/', t:'Saludos y Certificados RRHH', i:'bi-balloon-heart', d:'Los saludos automáticos (cumpleaños, aniversarios) y las plantillas de certificados de RRHH.',
  p:[['Edita la plantilla','El saludo sale solo el día que corresponde.']], n:null },
{ r:'/mantenedores/compras/', t:'Mantenedor Compras', i:'bi-bag-check', d:'La configuración del circuito de compras: niveles de aprobación por monto y categorías.',
  p:[['Define los niveles','Quién aprueba qué monto.']], n:null },
{ r:'/mantenedores/tickets-ti/', t:'Mantenedor Tickets TI', i:'bi-life-preserver', d:'La configuración de la mesa de ayuda: motivos, SLA por tipo y cadena de escalamiento.',
  p:[['Ajusta motivos y SLA','El escalamiento corre solo contra estos plazos.']], n:null },
{ r:'/mantenedores/definiciones/', t:'Definiciones', i:'bi-book', d:'El glosario del negocio: qué significa cada término del sistema (etapa, cartola, saldo insoluto…).',
  p:[['Busca el término','Lenguaje común para todo el equipo.']], n:null },
{ r:'/mantenedores/ayuda/', t:'Mantenedor de Ayuda', i:'bi-question-circle', d:'Edita el contenido del botón "?" de cada página: descripción, pasos, submódulos y siguiente paso. Lo que edites aquí NO se pisa con las actualizaciones.',
  p:[['Elige la página','Cada ruta tiene su ayuda editable.'],['Escribe para el usuario','Qué hace la página, cómo se usa y qué sigue.']],
  n:'La Academia reutiliza este mismo contenido como cursos.' },
{ r:'/mantenedores/documentacion/', t:'Documentación Business Suite', i:'bi-journal-richtext', d:'Los cinco documentos vivos del sistema: manual de usuario, procesos end-to-end, configuración maestro, documentación técnica y brochure.',
  p:[['Abre el documento','Cada uno se actualiza con los features en el mismo commit.']],
  n:'Un proceso sin documentar está incompleto: es máxima de la casa.' },
{ r:'/mantenedores/documentacion/capacitacion-ejecutivos.html/', t:'Manual de Capacitación Ejecutivos', i:'bi-mortarboard', d:'El manual de inducción del ejecutivo comercial: el paso a paso de su operación diaria en la plataforma.',
  p:[['Estudia por capítulos','Desde la evaluación hasta el seguimiento post venta.']],
  n:'Complementa los cursos de la Academia.' },

/* ═══ REPORTERÍA ═══ */
{ r:'/reporteria/diseno-consulta/', t:'Diseño de Consulta', i:'bi-diagram-3', d:'El constructor visual de reportes (estilo Access): eliges tablas, campos, filtros y agrupaciones, guardas la consulta y la reutilizas.',
  p:[['Arma la consulta','Arrastra tablas y campos; los JOIN se arman solos.'],['Filtra y agrupa','Condiciones y totales sin escribir SQL.'],['Guarda y comparte','La consulta guardada se reejecuta con datos frescos.']],
  n:'Para preguntas puntuales en lenguaje natural está Pregúntale a AutoFácil.' },
];
