'use strict';
/* ─────────────────────────────────────────────────────────────────────────────
   DÓNDE · CÓMO · QUIÉN — el banco de conocimiento operativo

   Cada entrada responde las tres preguntas de un usuario frente a la
   plataforma: DÓNDE se hace, CÓMO se hace y QUIÉN puede hacerlo.

   POR QUÉ ES UN BANCO PRECARGADO Y NO UNA IA: estas respuestas salen del
   código y de las reglas reales del sistema al momento de escribirlas. Una IA
   genérica no conoce la app y contestaría verosímil pero inventado — que en
   preguntas de "quién puede aprobar plata" es peor que no contestar.

   MANTENERLO VIVO: cuando un proceso cambie, la entrada se corrige ACÁ y el
   arranque converge la fila en BD (UPDATE por slug). Cada entrada:
     slug       identificador estable (no cambiarlo: es la llave de convergencia)
     cat        categoría visible
     p          la pregunta, como la diría un usuario
     donde      pantalla/módulo (con la ruta si existe)
     como       pasos, en lenguaje simple
     quien      perfil/permiso que puede hacerlo
     href       link directo (opcional)
     kw         palabras extra para la búsqueda (sinónimos, jerga interna)
   ───────────────────────────────────────────────────────────────────────────── */

module.exports = [

/* ═══ CRÉDITOS Y OPERACIONES ═══ */
{ slug:'credito-digitar', cat:'Créditos', p:'¿Dónde digito un crédito nuevo?',
  donde:'Créditos → Digitación (o el flujo desde una Carta de Aprobación).',
  como:'Las operaciones nuevas nacen de dos vías: digitación directa o creación desde una carta aprobada. El sistema asigna solo el N° OP correlativo (formato AAMM####).',
  quien:'Ejecutivos y Operaciones con permiso de digitación.', href:'/creditos/', kw:'crear operacion nueva ingresar digitar' },
{ slug:'numero-op-unico', cat:'Créditos', p:'¿Por qué el mismo crédito aparece con dos números distintos?',
  donde:'Ya no debería pasar: todas las pantallas operativas muestran el N° OP.',
  como:'Conviven dos numeraciones. El N° OP (AAMM####) es la llave de negocio de AutoFácil y es la que manda. El "número de crédito" (YYMM###, un dígito menos) nace en la carta de aprobación y sobrevive como dato de los documentos ya emitidos — por eso una carta impresa puede traerlo. Cobranza y Cuentas Transitorias aceptan los dos al buscar, así que un documento antiguo sigue encontrando su crédito.',
  quien:'Nadie los asigna a mano: el sistema los genera.', kw:'numero operacion credito dos numeros distinto carta correlativo' },
{ slug:'etapa-cancelado', cat:'Créditos', p:'¿Dónde quedaron los créditos CANCELADOS?',
  donde:'Se llaman RECHAZADOS.',
  como:'"CANCELADO" no existe como etapa y nunca vino de AutoFin: era una traducción de pantalla sobre los rechazados, que confundía porque no figuraba en ningún mantenedor. Las etapas son DIGITADO, CARTA_APROBACION, APROBADO, RECHAZADO, APELADO, OTORGADO, DESISTIDO y ANULADO. Los anulados tienen su propia etapa y NO se cuentan como rechazados.',
  quien:'—', kw:'cancelado cancelados rechazado etapa desaparecio no aparece' },
{ slug:'credito-carga-masiva', cat:'Créditos', p:'¿Cómo cargo operaciones desde un Excel?',
  donde:'Créditos → Carga Masiva.',
  como:'Se sube el Excel con el formato de la financiera. La llave anti-duplicados es (num_op, mes, financiera): recargar el mismo archivo no duplica. A cada ID de financiera nuevo se le asigna un N° OP propio.',
  quien:'Operaciones con permiso de carga masiva.', href:'/carga-masiva/', kw:'excel importar trinidad autofin subir masivo' },
{ slug:'eq-estados-autofin', cat:'Créditos', p:'¿Dónde veo las equivalencias de estados de AutoFin?',
  donde:'Carga Masiva → Equivalencias Trinidad (/carga-masiva/eq-estados/).',
  como:'Cada fila traduce un estado tal como viene escrito en el archivo de AutoFin (Trinidad) al estado equivalente de AutoFácil. Es lo que usa la carga al importar: por ejemplo "cursado" entra como "Otorgado". El calce NO distingue mayúsculas ni espacios sobrantes. Si un estado del archivo no está en la tabla, la operación entra como "Digitado" — así que si ves muchas digitadas después de una carga, revisa acá primero.',
  quien:'Quien tenga el permiso de carga Trinidad (cm_trinidad): Operaciones.', href:'/carga-masiva/eq-estados/',
  kw:'equivalencia equivalencias estados trinidad autofin mapeo traduccion homologacion cursado digitado' },
{ slug:'eq-ejecutivos-autofin', cat:'Créditos', p:'¿Dónde homologo los nombres de ejecutivos de AutoFin con los nuestros?',
  donde:'Carga Masiva → Equivalencia Ejecutivos (/carga-masiva/eq-ejecutivos/).',
  como:'Cada fila enlaza el nombre del ejecutivo como lo escribe AutoFin con el nombre nuestro. La carga lo traduce al importar. Si un nombre no está en la tabla, se guarda tal cual viene del archivo — por eso a veces aparece el mismo ejecutivo escrito de dos formas en los informes: falta la equivalencia.',
  quien:'Quien tenga el permiso de carga Trinidad (cm_trinidad): Operaciones.', href:'/carga-masiva/eq-ejecutivos/',
  kw:'equivalencia ejecutivos nombres trinidad autofin homologar vendedor duplicado' },
{ slug:'credito-anular', cat:'Créditos', p:'¿Cómo anulo una operación?',
  donde:'Módulo Anular Operación.',
  como:'Requiere DOBLE FIRMA de Operaciones: una persona solicita y otra confirma. Al anularse, la comisión del dealer se retira automáticamente de la cartola.',
  quien:'Operaciones (dos personas distintas: solicita + confirma).', kw:'anulacion eliminar operacion doble firma' },
{ slug:'credito-inmutable', cat:'Créditos', p:'¿Puedo modificar un crédito ya otorgado?',
  donde:'No se puede desde ninguna pantalla estándar.',
  como:'Al otorgar, TODO queda congelado (tabla de cuotas incluida). Es una regla de diseño: lo otorgado es inmutable. Correcciones excepcionales pasan por los Editores de BD con nivel.',
  quien:'Solo editores BD nivel "Solo Dios" (todo) o "Analista" (meses abiertos).', kw:'editar cambiar otorgado congelado inmutable' },
{ slug:'credito-respaldos-cerrada', cat:'Créditos', p:'¿Dónde veo los respaldos de una operación ya otorgada o cerrada?',
  donde:'Créditos → Revisión → botón "Ver Respaldos".',
  como:'En operaciones cerradas (OTORGADO, DESISTIDO, CURSADO…) la pantalla se abre en modo lectura: se ven y descargan los documentos, pero no se puede subir ni borrar.',
  quien:'Cualquier usuario con acceso a Revisión de Créditos.', href:'/creditos/revisar', kw:'documentos ver archivos operacion cerrada otorgada' },
{ slug:'credito-prepago', cat:'Créditos', p:'¿Cómo se hace un prepago de un crédito?',
  donde:'Tesorería → Caja (Prepago en Caja).',
  como:'El monto lo calcula el motor único de prepago (capital + accesorios, distinto del saldo insoluto). Se emite el certificado y el comprobante sale con copia a cobranza.',
  quien:'Cajeros con caja activa.', kw:'prepagar adelantar pagar todo certificado' },
{ slug:'credito-pagar-cuota', cat:'Créditos', p:'¿Quién puede pagar una cuota y dónde?',
  donde:'Tesorería → Caja (pago de cuotas) o vía Orden de Pago.',
  como:'En caja se busca la operación, se selecciona la(s) cuota(s) y se registra el pago. El movimiento se contabiliza automáticamente por el motor de asientos.',
  quien:'Cajeros con caja activa abierta a su nombre.', kw:'abonar cuota pagar caja recibo' },
{ slug:'credito-castigo', cat:'Créditos', p:'¿Cómo se castiga el saldo de un crédito?',
  donde:'Módulo Castigar Saldo.',
  como:'Requiere DOBLE FIRMA GERENCIAL. El castigo tiene además un cierre automático mensual y las provisiones se calculan solas.',
  quien:'Dos firmas de nivel gerencial.', kw:'castigo incobrable provision perdida' },
{ slug:'credito-bitacora', cat:'Créditos', p:'¿Dónde veo todo lo que le ha pasado a un crédito?',
  donde:'Bitácora de un Crédito.',
  como:'Se busca por RUT o N° OP y muestra el timeline completo de eventos, solo lectura.',
  quien:'Cualquier usuario con el permiso del módulo.', kw:'historial timeline eventos linea tiempo' },
{ slug:'credito-estados', cat:'Créditos', p:'¿Quién define los estados de un crédito y sus transiciones?',
  donde:'Mantenedores → Estado Créditos.',
  como:'Es una máquina de estados paramétrica por ámbito (brokerage hoy). Se configuran estados, colores, orden y qué transiciones se permiten. Por ahora dibuja el flujo; el bloqueo duro se activará cuando el mapa esté validado.',
  quien:'Administrador.', href:'/mantenedores/estado-creditos/', kw:'flujo maquina estados transiciones digitado aprobado otorgado' },
{ slug:'credito-numeracion', cat:'Créditos', p:'¿Qué diferencia hay entre el N° OP y el ID de la financiera?',
  donde:'En toda pantalla de créditos aparecen ambos.',
  como:'El N° OP es NUESTRO correlativo único (AAMM####) y es la clave del negocio. El ID financiera es el número que asigna AutoFin/Unidad: referencia externa, va en su columna propia. Nunca se usa el de la financiera como número de operación.',
  quien:'El sistema lo asigna solo; nadie lo digita.', kw:'numero operacion op id financiera correlativo' },
{ slug:'credito-restauracion', cat:'Créditos', p:'¿Se puede volver el sistema a un punto anterior (deshacer una carga)?',
  donde:'Punto de Restauración (herramienta UAT).',
  como:'Borra créditos y tablas hijas posteriores a una marca de tiempo. Es una herramienta de pruebas, no de producción diaria.',
  quien:'Solo perfil "Solo Dios".', kw:'deshacer rollback restaurar borrar carga' },

/* ═══ CARTAS DE APROBACIÓN ═══ */
{ slug:'carta-emitir', cat:'Cartas', p:'¿Cómo emito una carta de aprobación?',
  donde:'Módulo Cartas de Aprobación.',
  como:'Se completa la ficha del cliente y la operación (puede autocompletarse desde el PDF de Unidad), se emite y queda con su N° de carta. La participación del dealer que dice la carta ES la comisión que rige.',
  quien:'Ejecutivos comerciales; la aprobación depende del flujo configurado.', kw:'emitir carta aprobacion generar' },
{ slug:'carta-comision-manda', cat:'Cartas', p:'¿Qué comisión se le paga al dealer: la de la tabla o la de la carta?',
  donde:'La carta manda.',
  como:'La participación pactada en la carta al emitirla es un snapshot deliberado: aunque después cambie la tabla del dealer, la operación paga lo que decía SU carta.',
  quien:'Definido al emitir la carta.', kw:'participacion dealer comision pactada snapshot' },
{ slug:'carta-vencimiento', cat:'Cartas', p:'¿Cuánto dura vigente una carta y qué pasa si vence?',
  donde:'Cartas Vigentes → Otorgar/Desistir.',
  como:'El plazo es configurable (5 días por defecto). Vencida, la operación no se puede otorgar con esa carta: se emite una nueva. Por eso una operación puede tener una carta vencida/anulada y otra aprobada — vale la APROBADA.',
  quien:'El vencimiento corre solo; re-emitir es del ejecutivo.', kw:'vence plazo vigencia desistir renovar' },
{ slug:'carta-seguimiento-wsp', cat:'Cartas', p:'¿Se puede hacer seguimiento de cartas por WhatsApp?',
  donde:'Seguimiento de Cartas WSP.',
  como:'El sistema envía seguimiento por WhatsApp (Meta Cloud) según la plantilla aprobada.',
  quien:'Configuración del área comercial.', kw:'whatsapp seguimiento notificacion carta' },

/* ═══ COMISIONES Y CARTOLAS ═══ */
{ slug:'comision-revision', cat:'Comisiones', p:'¿Dónde reviso las comisiones del mes de los ejecutivos?',
  donde:'Comisiones → Revisión.',
  como:'Muestra el cálculo mensual por ejecutivo (piso + incentivo + ajustes por cumplimiento). Cada usuario ve solo los ejecutivos que tiene asignados.',
  quien:'Jefaturas y quien tenga ejecutivos asignados en usuario_ejecutivos.', href:'/comisiones/revision/', kw:'revision comisiones ejecutivo mensual sueldo variable' },
{ slug:'comision-dealer-motor', cat:'Comisiones', p:'¿Cómo se calcula la comisión de un dealer?',
  donde:'Motor único de comisión dealer.',
  como:'Si el dealer tiene tabla individual, esa manda; si no, rige la pizarra (tabla general). El resultado queda pactado en la carta al emitirla.',
  quien:'La tabla individual se configura por dealer en su ficha.', kw:'calculo comision concesionario tabla pizarra' },
{ slug:'comision-iva', cat:'Comisiones', p:'¿Las comisiones son con IVA o sin IVA?',
  donde:'Regla transversal del sistema.',
  como:'La comisión se pacta y registra BRUTA (IVA incluido, siempre). Para desagregar se usa el motor de impuestos con la tasa del mantenedor.',
  quien:'Regla fija; el IVA se configura en el mantenedor de impuestos.', kw:'bruto neto iva impuesto desagregar' },
{ slug:'cartola-que-es', cat:'Comisiones', p:'¿Cómo funciona la cartola del dealer?',
  donde:'Post Venta → Cartolas.',
  como:'Es acumulativa por estado: cada operación otorgada genera su movimiento de comisión (PENDIENTE → A PAGAR → …). La factura del dealer debe calzar con el TOTAL de la cartola. Regla de oro: lo que no está OTORGADO no entra a cartola.',
  quien:'Post Venta administra; el dealer la recibe.', kw:'cartola estado cuenta dealer movimientos' },
{ slug:'cartola-factura', cat:'Comisiones', p:'¿Contra qué se factura la comisión del dealer?',
  donde:'Post Venta → Facturación / Consulta Factura.',
  como:'La factura del dealer es por el total de su cartola del período. La boleta (si aplica) es por el líquido. La retención va al F29 automáticamente.',
  quien:'Post Venta valida; contabilidad se genera sola.', kw:'facturar factura boleta retencion honorarios' },
{ slug:'comision-anulada', cat:'Comisiones', p:'Si se anula una operación, ¿qué pasa con la comisión del dealer?',
  donde:'Automático al anular.',
  como:'La anulación retira el movimiento de comisión de la cartola. Si ya estaba pagada, el caso pasa a gestión manual con Post Venta.',
  quien:'Se dispara solo con la anulación (doble firma).', kw:'anular operacion comision devolver retirar' },
{ slug:'comision-parque', cat:'Comisiones', p:'¿Cómo se paga el arriendo de un parque automotriz?',
  donde:'Post Venta → Comisiones Parques.',
  como:'Es un monto fijo mensual que se PRORRATEA entre las operaciones otorgadas del mes en ese parque. Nunca es un fee por operación.',
  quien:'Configurado por parque; el cálculo es automático.', kw:'parque arriendo prorrateo mensual' },
{ slug:'bono-jefe', cat:'Comisiones', p:'¿Cómo se calcula el bono del Jefe Comercial?',
  donde:'Módulo Bono Jefe Comercial.',
  como:'Es un BSC (balanced scorecard) con topes por indicador y curva exponencial de cumplimiento.',
  quien:'Parámetros los define Gerencia; el cálculo es automático.', kw:'bono bsc scorecard jefe comercial' },

/* ═══ ÓRDENES DE PAGO ═══ */
{ slug:'odp-emitir', cat:'Órdenes de Pago', p:'¿Cómo emito una orden de pago?',
  donde:'Órdenes de Pago (proveedores) o Post Venta → Orden de Pago (saldo precio / comisión).',
  como:'Se selecciona el beneficiario y el concepto; el correlativo OP- es único y central para todos los orígenes. La ODP genera su asiento contable automáticamente.',
  quien:'Quien tenga el permiso ordenes_pago_emitir.', href:'/ordenes-pago/historial/', kw:'orden pago odp emitir generar proveedor' },
{ slug:'odp-anular', cat:'Órdenes de Pago', p:'¿Cómo anulo una orden de pago ya emitida?',
  donde:'Órdenes de Pago → Historial → botón Anular en la orden.',
  como:'Solo órdenes de Post Venta (saldo precio / comisión) EMITIDAS y no pagadas. Pide un motivo de al menos 10 caracteres, libera el correlativo y deshace las etapas de Post Venta asociadas.',
  quien:'Solo Administrador.', href:'/ordenes-pago/historial/', kw:'anular odp orden emitida deshacer' },
{ slug:'odp-pagar', cat:'Órdenes de Pago', p:'¿Quién puede pagar una orden de pago?',
  donde:'Órdenes de Pago → desde la orden, acción Pagar.',
  como:'El requisito real es tener una CAJA ACTIVA abierta: sin caja no hay botón de pago. El pago rebaja el pasivo contra banco (devengo y pago son dos hechos contables distintos).',
  quien:'Cajeros con caja activa a su nombre.', kw:'pagar odp caja transferencia egreso' },
{ slug:'odp-postventa-bloquea', cat:'Órdenes de Pago', p:'¿Por qué no puedo desmarcar una etapa de Post Venta que dice "Orden de Pago emitida"?',
  donde:'Post Venta → Seguimiento.',
  como:'Esa etapa la marca el sistema al emitir la ODP y no se desmarca a mano: se deshace ANULANDO la orden (Historial de ODP → Anular). Al anularla, las etapas se deshacen solas.',
  quien:'Anular la ODP: solo Administrador.', href:'/ordenes-pago/historial/', kw:'desmarcar etapa candado orden emitida postventa' },

/* ═══ TESORERÍA Y CAJA ═══ */
{ slug:'caja-abrir', cat:'Tesorería', p:'¿Cómo abro mi caja para operar?',
  donde:'Tesorería → Cajas.',
  como:'Cada cajero abre SU caja; los pagos y cobros del día quedan asociados a ella. Sin caja activa no se puede pagar ODP ni recibir pagos.',
  quien:'Cajeros habilitados.', kw:'caja abrir activa cerrar arqueo' },
{ slug:'tesoreria-transitorias', cat:'Tesorería', p:'¿Para qué sirven las cuentas transitorias?',
  donde:'Tesorería → Cuentas Transitorias.',
  como:'Registran plata que entró y aún no se aplica a su destino final. El JOIN con créditos es por ID interno, y la aplicación posterior genera su asiento.',
  quien:'Tesorería.', href:'/tesoreria/cuentas-transitorias/', kw:'transitoria aplicar identificar deposito' },
{ slug:'tesoreria-conciliacion', cat:'Tesorería', p:'¿Cómo se concilian los movimientos bancarios?',
  donde:'Conexiones Bancarias → Conciliación.',
  como:'Los movimientos llegan por Fintoc y el matching automático propone el calce contra lo esperado; lo que no calza queda para revisión manual.',
  quien:'Tesorería.', kw:'banco conciliar fintoc cartola bancaria matching' },
{ slug:'tesoreria-cierre', cat:'Tesorería', p:'¿Cómo se hace el cierre contable mensual?',
  donde:'Tesorería → Cierre Contable.',
  como:'Genera el informe mensual (el que va a Ecuador) con la cuadratura del período. Se apoya en el checklist de Cierre de Mes con responsables, recordatorios y candado + acta.',
  quien:'Tesorería/Contabilidad; el candado lo pone quien cierra.', kw:'cierre mes informe ecuador cuadratura candado' },
{ slug:'fondos-aplicar', cat:'Tesorería', p:'¿Cómo aplico fondos recibidos a un crédito?',
  donde:'Aplicación de Fondos.',
  como:'Permite descuento por ítem sobre el motor de prepago, con firmas HECHO → PROCESADO.',
  quien:'Tesorería con las dos firmas del flujo.', kw:'aplicar fondos abono descuento item' },

/* ═══ COBRANZA ═══ */
{ slug:'cobranza-automatica', cat:'Cobranza', p:'¿Qué gestiona automáticamente la cobranza?',
  donde:'Cobranza → Automatizaciones.',
  como:'Correo por tramo de mora y WhatsApp, respetando la Ley 21.320 (horarios y frecuencias permitidas). Los parámetros de cada tramo son configurables.',
  quien:'Los motores corren solos; los parámetros los ajusta el Administrador.', kw:'correo automatico whatsapp mora tramo ley' },
{ slug:'cobranza-mora-tasa', cat:'Cobranza', p:'¿Con qué tasa se calcula el interés por mora?',
  donde:'Mantenedor de parámetros de cobranza.',
  como:'El motor es paramétrico (mora_tasa_modo): por defecto usa la TMC FIJA al momento del otorgamiento del crédito, no la vigente al día del atraso.',
  quien:'Administrador define el modo; el cálculo es del motor único.', kw:'interes mora tmc tasa penal atraso' },
{ slug:'cobranza-condonar', cat:'Cobranza', p:'¿Puedo condonar deuda? ¿En qué orden?',
  donde:'Gestión de cobranza sobre la operación.',
  como:'El orden es fijo: PRIMERO gastos de cobranza, LUEGO intereses. El capital NUNCA se condona.',
  quien:'Según atribuciones del perfil de cobranza.', kw:'condonacion perdonar rebajar gastos intereses' },
{ slug:'cobranza-terreno', cat:'Cobranza', p:'¿Cómo funciona la cobranza en terreno?',
  donde:'PWA Terreno (aplicación instalable en el teléfono).',
  como:'El gestor ve su ruta del día, hace check-in con GPS y sube fotos de la visita. Es la única pantalla donde el token vive en el teléfono para trabajar sin señal.',
  quien:'Gestores de terreno.', kw:'terreno visita ruta gps pwa celular' },
{ slug:'cobranza-score', cat:'Cobranza', p:'¿Qué es el score de mora?',
  donde:'Módulo Score de Mora.',
  como:'Calcula mora histórica por segmento para priorizar gestión.',
  quien:'Cobranza lo consulta; el cálculo es automático.', kw:'score riesgo mora historica segmento' },

/* ═══ POST VENTA ═══ */
{ slug:'pv-etapas', cat:'Post Venta', p:'¿Por qué algunas etapas de Post Venta no se pueden marcar o desmarcar?',
  donde:'Post Venta → Seguimiento.',
  como:'Las etapas automáticas las marca el sistema (fundantes recibidos, ODP emitida…) y se deshacen desde su módulo dueño, no a mano. Además el orden se respeta: no se marca una etapa si falta la anterior, y desmarcar solo se puede el mismo día. Al pasar el mouse por el candado aparece el porqué y el link al módulo que corresponde.',
  quien:'Etapas manuales: Post Venta. Automáticas: solo su módulo dueño.', kw:'etapa candado bloqueada desmarcar checkbox seguimiento' },
{ slug:'pv-saldo-precio', cat:'Post Venta', p:'¿Cómo se paga el saldo de precio al dealer?',
  donde:'Post Venta → Orden de Pago (saldo precio).',
  como:'Se emite la ODP del saldo contra los datos bancarios de la ficha del dealer; al emitirla se marca la etapa correspondiente en Seguimiento.',
  quien:'Post Venta emite; paga quien tenga caja activa.', kw:'saldo precio pagar dealer transferencia' },
{ slug:'pv-consulta-saldos', cat:'Post Venta', p:'¿Dónde consulto los saldos pendientes de pago a dealers?',
  donde:'Post Venta → Consulta Saldos.',
  como:'Muestra el estado de saldos de precio por operación y dealer.',
  quien:'Post Venta y perfiles con el permiso.', kw:'saldos pendientes dealer consulta' },

/* ═══ FUNDANTES ═══ */
{ slug:'fund-subir', cat:'Fundantes', p:'¿Cómo subo los documentos fundantes de una operación?',
  donde:'Seguimiento Fundantes → Ejecutivo Comercial.',
  como:'Cada operación otorgada muestra sus columnas de documentos (compraventa, transferencia, limitación…). Se sube cada uno y, cuando están todos los obligatorios, se habilita Enviar a validación.',
  quien:'El ejecutivo comercial de la operación.', href:'/fundantes-seguimiento/', kw:'fundantes subir documentos compraventa transferencia enviar' },
{ slug:'fund-validar', cat:'Fundantes', p:'¿Quién valida los fundantes enviados?',
  donde:'Seguimiento Fundantes → Operaciones.',
  como:'Operaciones revisa el set completo (puede bajarlo en ZIP), aprueba o rechaza con motivo. El rechazo devuelve la operación al ejecutivo para corregir.',
  quien:'Operaciones (permiso fundantes_validar).', kw:'validar aprobar rechazar zip operaciones' },
{ slug:'fund-gps-opcional', cat:'Fundantes', p:'¿El Informe GPS es obligatorio?',
  donde:'Definido en Mantenedores → Documentos Fundantes.',
  como:'Desde agosto 2026 es OPCIONAL: se puede subir y queda a la vista, pero no traba el envío. Si mañana debe volver a ser obligatorio, se cambia en el mantenedor, sin programador.',
  quien:'Administrador (mantenedor Documentos Fundantes).', href:'/mantenedores/fundantes-tipos/', kw:'gps informe opcional obligatorio' },
{ slug:'fund-tipos-mantenedor', cat:'Fundantes', p:'¿Dónde configuro qué documentos pide cada financiera?',
  donde:'Mantenedores → Documentos Fundantes.',
  como:'Se agrega/edita cada documento con su exigencia: Obligatorio, Opcional o "Solo si viene contratado" (GPS/limitación). No se puede eliminar uno con archivos ya cargados: se marca opcional.',
  quien:'Administrador (permiso fundantes_tipos).', href:'/mantenedores/fundantes-tipos/', kw:'tipos documentos financiera exigencia configurar' },
{ slug:'fund-devueltos', cat:'Fundantes', p:'¿Qué pasa si la financiera devuelve fundantes ya aprobados?',
  donde:'Seguimiento Fundantes → Devueltos.',
  como:'La operación pasa a DEVUELTO, el ejecutivo corrige y reenvía. El historial conserva el primer resultado y el estado final.',
  quien:'Operaciones registra la devolución; corrige el ejecutivo.', kw:'devuelto devolucion financiera corregir reenviar' },

/* ═══ DEALERS ═══ */
{ slug:'dealer-crear', cat:'Dealers', p:'¿Cómo se crea un dealer nuevo?',
  donde:'Creación/Mantenedor de Dealer (Dealers Incorporación).',
  como:'Se llena la ficha del concesionario y pasa por la cadena de aprobación paramétrica (niveles configurables). La ficha se imprime en UNA sola hoja carta y vuelve firmada.',
  quien:'Comercial inicia; aprueban los niveles configurados.', href:'/dealers-incorporacion/', kw:'crear dealer concesionario ficha incorporacion alta' },
{ slug:'dealer-ficha-firmada', cat:'Dealers', p:'¿Por qué me rechazaron la ficha del dealer firmada?',
  donde:'Dealers Incorporación → la ficha, en su historial.',
  como:'La causa más común: la ficha debe venir firmada EN UNA SOLA página. Desde v176.1 el sistema ajusta solo el tamaño para que siempre quepa en una hoja carta, sin importar cuántos socios tenga.',
  quien:'Rechaza/aprueba el nivel de Operaciones/Crédito.', kw:'ficha rechazada firmada una pagina hoja' },
{ slug:'dealer-comision-tabla', cat:'Dealers', p:'¿Dónde configuro la comisión especial de un dealer?',
  donde:'Ficha del dealer → su tabla individual de comisiones.',
  como:'Si existe tabla individual, manda sobre la pizarra general. La operación concreta paga lo pactado en su carta.',
  quien:'Quien administre dealers con ese permiso.', kw:'tabla individual comision especial dealer' },
{ slug:'dealer-portal', cat:'Dealers', p:'¿Qué puede hacer el dealer en su portal?',
  donde:'Portal del Dealer (acceso externo).',
  como:'Self-service: pre-aprobación automática de clientes según políticas paramétricas, seguimiento de sus operaciones y documentos.',
  quien:'Cuentas del dealer (fuera del staff; sus tokens no entran a rutas internas).', kw:'portal dealer preaprobacion externo' },
{ slug:'dealer-visitas', cat:'Dealers', p:'¿Cómo se planifican las visitas a dealers?',
  donde:'Ruta AutoFácil (visitas) + Mapa de Dealers.',
  como:'Calendario con asignación masiva de visitas; el mapa usa geocodificación de las direcciones.',
  quien:'Jefatura comercial asigna; ejecutivos visitan.', kw:'visitas ruta mapa calendario terreno' },
{ slug:'dealer-potencial', cat:'Dealers', p:'¿Cómo se mide el potencial de un dealer o parque?',
  donde:'Potencial Parque/Dealer.',
  como:'Fórmula de potencial + categoría configurable en su mantenedor.',
  quien:'Consulta comercial; parámetros del Administrador.', kw:'potencial categoria parque medicion' },
{ slug:'dealer-vendedores', cat:'Dealers', p:'¿De dónde sale el vendedor de una operación?',
  donde:'Vendedores con Ventas + Detalle Mensual.',
  como:'El vendedor sale de la CARTA de aprobación, no del crédito. Si está mal, se corrige en la carta.',
  quien:'Quien emite la carta lo registra.', kw:'vendedor carta ventas detalle' },

/* ═══ CLIENTES Y EVALUACIÓN ═══ */
{ slug:'eval-consultar', cat:'Evaluación', p:'¿Cómo evalúo a un cliente nuevo?',
  donde:'Evaluación Crediticia.',
  como:'Se ingresa el RUT y el sistema arma la ficha (integración DealerNet para el informe). Se elige la ocupación —queda guardada para la próxima— y se cargan los documentos que esa ocupación exige. La política V3.0 aplica scorecard por quintiles.',
  quien:'Ejecutivos y analistas de crédito.', href:'/evaluacion-crediticia/', kw:'evaluar cliente rut scorecard politica dealernet informe' },
{ slug:'cliente-datos-unicos', cat:'Evaluación', p:'¿Dónde se corrigen los datos personales de un cliente?',
  donde:'Módulo Clientes.',
  como:'Los datos personales viven en UNA sola fuente (tabla clientes, única por RUT); antecedentes laborales e información comercial son tablas satélite. Todo lo demás (cartas, cobranza, dashboard) LEE de ahí — corregir en la fuente corrige en todas partes.',
  quien:'Quien tenga permiso de edición de clientes.', kw:'datos cliente direccion telefono corregir fuente unica' },
{ slug:'eval-alertas', cat:'Evaluación', p:'¿Cómo sé que llegó una operación para analizar?',
  donde:'Campanita de avisos.',
  como:'Al entrar una operación EN_ANALISIS se avisa al pool de analistas; el aviso se retira solo cuando alguien la toma.',
  quien:'Pool de análisis.', kw:'alerta analisis aviso campana pool' },

/* ═══ USUARIOS, PERMISOS Y SEGURIDAD ═══ */
{ slug:'usuario-crear', cat:'Usuarios', p:'¿Cómo creo un usuario nuevo?',
  donde:'Usuarios → Gestión de usuarios.',
  como:'Se crea con su perfil; la clave temporal exige cambio al primer ingreso. El menú y las cards que verá dependen 100% de su perfil (matriz de permisos).',
  quien:'Administrador; un editor no-Admin solo puede otorgar perfiles contenidos en sus propios permisos.', href:'/usuarios/', kw:'crear usuario alta cuenta nueva' },
{ slug:'usuario-permisos', cat:'Usuarios', p:'¿Quién decide qué puede ver y hacer cada perfil?',
  donde:'Usuarios → Perfiles y Permisos.',
  como:'Matriz por funcionalidad: cada casilla habilita una pantalla (href) o una acción (sin href). Los módulos y sub-items del home salen de esta matriz — no hay menús fijos en código. Existe además override individual por usuario.',
  quien:'Administrador.', href:'/usuarios/', kw:'perfil permisos matriz funcionalidad habilitar rol' },
{ slug:'usuario-suspender', cat:'Usuarios', p:'¿Qué pasa cuando suspendo a un usuario?',
  donde:'Usuarios → editar → estado inactivo.',
  como:'Sus sesiones abiertas SE CIERRAN EN EL ACTO (no al vencer el token) y no puede volver a entrar. El finiquito en RRHH lo suspende automáticamente.',
  quien:'Administrador; RRHH vía finiquito.', kw:'suspender desactivar baja desvincular sesion' },
{ slug:'usuario-clave', cat:'Usuarios', p:'¿Cómo se resetea la clave de un usuario?',
  donde:'Usuarios → acción Resetear clave.',
  como:'Genera clave temporal con cambio forzado al ingresar, desbloquea la cuenta y CIERRA todas las sesiones anteriores (si se resetea es porque se sospecha del acceso). La temporal cumple siempre la política vigente (mayúscula, número y símbolo) y evita caracteres que se confunden al dictarla por teléfono.',
  quien:'Administrador — y solo sobre usuarios cuyo perfil él mismo podría otorgar: no se puede resetear la clave de alguien con más permisos que uno. La cuenta protegida de emergencia no se resetea desde acá.',
  kw:'clave contrasena resetear olvido bloqueo temporal' },
{ slug:'clave-reglas', cat:'Usuarios', p:'¿Qué requisitos tiene que cumplir una contraseña?',
  donde:'Los define el Administrador en Usuarios → Seguridad (largo mínimo, mayúscula, número, carácter especial, no repetir las últimas N).',
  como:'Las reglas se validan EN EL SERVIDOR cada vez que alguien fija una clave, no solo en la pantalla: si no cumple, el sistema dice exactamente qué le falta. Cambiar una regla rige de inmediato para el próximo cambio. Quien ya tenga una clave que no cumple puede seguir entrando (la política se aplica al CAMBIARLA); para forzar la renovación de todos se usa "Vencimiento de clave". La cuenta protegida de emergencia queda exenta a propósito.',
  quien:'Las configura el Administrador; las cumple todo el mundo.', href:'/usuarios/',
  kw:'contrasena clave requisitos politica seguridad mayuscula numero simbolo historial largo minimo' },
{ slug:'clave-obligatoria', cat:'Usuarios', p:'El sistema no me deja hacer nada hasta cambiar la clave, ¿por qué?',
  donde:'Te pasa al primer ingreso, después de un reseteo, o cuando venció el plazo configurado.',
  como:'El bloqueo es del servidor, no un aviso de la pantalla: hasta que cambies la contraseña solo se te permite esa acción. Al cambiarla, el sistema te devuelve la sesión ya habilitada y sigues trabajando sin volver a entrar.',
  quien:'Cualquier usuario alcanzado por la política.', kw:'cambiar clave obligatorio primer ingreso vencida forzado bloqueado' },
{ slug:'usuario-bloqueo', cat:'Usuarios', p:'Me bloqueó el login por intentos fallidos, ¿qué hago?',
  donde:'Lo desbloquea un administrador en Usuarios.',
  como:'Tras N intentos fallidos (paramétrico) la cuenta se bloquea. OJO: bloqueo NO es suspensión — el reseteo de clave también desbloquea.',
  quien:'Administrador.', kw:'bloqueado intentos fallidos login entrar' },
{ slug:'usuario-visibilidad', cat:'Usuarios', p:'¿Por qué un usuario ve solo algunos ejecutivos en comisiones?',
  donde:'Usuarios → asignación de ejecutivos.',
  como:'La tabla usuario_ejecutivos controla qué ejecutivos ve cada usuario; la visibilidad se aplica en todos los módulos que la usan.',
  quien:'Administrador asigna.', kw:'ver ejecutivos visibilidad asignados filtro' },
{ slug:'seguridad-sesion', cat:'Usuarios', p:'¿Cuánto dura una sesión y por qué me pidió entrar de nuevo?',
  donde:'Regla de plataforma.',
  como:'La sesión dura 8 horas. Además se cierra al instante si: te suspendieron, te cambiaron el perfil o te resetearon la clave. El token vive solo en la pestaña (sessionStorage): cerrar el navegador la termina.',
  quien:'Automático.', kw:'sesion expiro 8 horas deslogueo token' },
{ slug:'seguridad-auditoria', cat:'Usuarios', p:'¿Quedan registradas las acciones críticas? ¿Dónde las veo?',
  donde:'Módulo Auditoría.',
  como:'Las acciones sensibles (logins, ediciones de usuarios, anulaciones, cargas, cierres) quedan en el log con quién, qué y cuándo.',
  quien:'Perfiles con acceso a Auditoría.', href:'/auditoria/', kw:'auditoria log registro quien hizo' },
{ slug:'seguridad-consola', cat:'Usuarios', p:'¿Se puede consultar la base de datos directamente?',
  donde:'Consola SQL.',
  como:'Solo LECTURA y cada consulta queda auditada.',
  quien:'Exclusivo perfil "Solo Dios".', kw:'sql consola consulta base datos' },

/* ═══ MANTENEDORES ═══ */
{ slug:'mant-uf', cat:'Mantenedores', p:'¿Dónde se cargan los valores de la UF?',
  donde:'Mantenedores → UF (y sincronización automática de indicadores).',
  como:'La UF, UTM, dólar y TMC se sincronizan solos desde la API de la CMF; el mantenedor permite ver y corregir valores históricos. Todo cálculo usa getUF(fecha) — un solo motor.',
  quien:'El motor sincroniza; corrige el Administrador.', kw:'uf utm dolar tmc indicadores valores' },
{ slug:'mant-tasas', cat:'Mantenedores', p:'¿Dónde configuro las tasas de los créditos?',
  donde:'Mantenedores → Tasas.',
  como:'Tablas de tasas por producto/plazo. El footer del mantenedor lista qué pantallas y procesos afecta cada variable.',
  quien:'Administrador.', kw:'tasa interes producto plazo configurar' },
{ slug:'mant-avisos', cat:'Mantenedores', p:'¿Cómo configuro los avisos (la campanita)?',
  donde:'Mantenedor de Avisos.',
  como:'Motor único de avisos: cada regla define cuándo suena y a quién. Si una campanita "no se calla", casi siempre es porque el paso siguiente del flujo no retiró el aviso del paso anterior.',
  quien:'Administrador.', kw:'campana avisos notificacion alertas configurar' },
{ slug:'mant-workflows', cat:'Mantenedores', p:'¿Cómo funcionan los flujos de aprobación (workflows)?',
  donde:'Workflows y Escalamiento.',
  como:'15 flujos con quiénes aprueban en cada paso, plazos en horas hábiles y escalamiento a jefatura si no responden. Todo queda en el log del workflow.',
  quien:'Administrador configura; aprueban los designados.', kw:'workflow aprobacion escalamiento pasos flujo' },
{ slug:'mant-cierre-mes', cat:'Mantenedores', p:'¿Cómo se cierra el mes?',
  donde:'Cierre de Mes (checklist).',
  como:'Checklist con responsables y recordatorios; al completarse se pone el CANDADO del período y se firma el acta. Un mes cerrado no acepta modificaciones (los recálculos lo respetan).',
  quien:'Cada responsable su ítem; el candado, quien preside el cierre.', kw:'cierre mes candado acta periodo' },
{ slug:'mant-forzados', cat:'Mantenedores', p:'¿Qué significan los valores en azul y en rojo en las pantallas de edición?',
  donde:'Editores de BD y pantallas de cálculo.',
  como:'AZUL = calculado por fórmula. ROJO = forzado a mano. El recálculo automático respeta los forzados y los meses cerrados.',
  quien:'Forzar valores requiere el nivel de editor correspondiente.', kw:'azul rojo forzado formula calculado recalculo' },
{ slug:'mant-docs', cat:'Mantenedores', p:'¿Dónde está la documentación oficial de los procesos?',
  donde:'Mantenedores → Documentación.',
  como:'Cinco documentos vivos: manual de usuario, procesos end-to-end, configuración maestra, técnica y brochure. Cada proceso nuevo nace documentado ahí.',
  quien:'Lectura general; edita quien desarrolla.', kw:'manual documentacion procesos ayuda' },
{ slug:'mant-apis', cat:'Mantenedores', p:'¿Cómo doy acceso a la API pública a una empresa externa?',
  donde:'Mantenedores → APIs.',
  como:'Se crea la empresa y su X-API-Key; el simulador de cotización queda disponible para esa llave.',
  quien:'Administrador.', href:'/mantenedores/apis/', kw:'api key externa integracion simulador' },

/* ═══ CONTABILIDAD ═══ */
{ slug:'ctb-automatica', cat:'Contabilidad', p:'¿Tengo que digitar los asientos contables?',
  donde:'No — Contabilidad se construye sola.',
  como:'Cada movimiento de dinero genera su asiento por el motor único de centralización, según las reglas paramétricas del mantenedor Reglas de Centralización. Si algo queda SIN_REGLA en el log de eventos, falta cablear esa regla.',
  quien:'Nadie digita; el Administrador cablea reglas.', kw:'asiento automatico centralizacion regla contabilizar' },
{ slug:'ctb-sin-regla', cat:'Contabilidad', p:'¿Qué significa SIN_REGLA en contabilidad?',
  donde:'Contabilidad → log de eventos (ctb_eventos_log).',
  como:'Un movimiento ocurrió y no encontró regla contable: NO bloqueó la operación (la contabilidad nunca bloquea), pero quedó pendiente de cablear. Ese log es la lista de tareas contables.',
  quien:'Contabilidad/Administrador crea la regla faltante.', kw:'sin regla descuadre evento log pendiente' },
{ slug:'ctb-f29', cat:'Contabilidad', p:'¿El F29 sale del sistema?',
  donde:'Contabilidad (impuestos).',
  como:'IVA débito/crédito y retenciones van a sus cuentas en cada asiento, así el F29 se arma desde el sistema y no a mano. El libro de compras llega del SII vía SimpleAPI.',
  quien:'Contabilidad lo revisa; los impuestos se registran solos.', kw:'f29 iva retencion impuesto declaracion sii' },
{ slug:'ctb-periodos', cat:'Contabilidad', p:'¿Por qué no debo crear cuentas contables con el año en el nombre?',
  donde:'Regla del plan de cuentas.',
  como:'La separación por ejercicio la da el PERÍODO contable, no cuentas distintas. "FACTURAS POR PAGAR 2025" está prohibido.',
  quien:'Regla fija para quien administre el plan de cuentas.', kw:'cuenta año ejercicio periodo plan' },
{ slug:'ctb-ordenes-compra', cat:'Contabilidad', p:'¿Cómo se aprueba una compra interna?',
  donde:'Compras (Soporte) → workflow por niveles + Revisión de Órdenes.',
  como:'La solicitud pasa por los niveles configurados según monto; aprobada genera su orden y su registro contable.',
  quien:'Aprueban los niveles del workflow de compras.', kw:'compra solicitud aprobar orden niveles' },

/* ═══ RRHH ═══ */
{ slug:'rrhh-ficha', cat:'RRHH', p:'¿Dónde está la ficha del trabajador?',
  donde:'RRHH → ficha estilo Buk.',
  como:'Ficha + carpeta de documentos del trabajador. Las remuneraciones fueron validadas al peso contra AVSOFT.',
  quien:'RRHH.', kw:'trabajador ficha carpeta contrato remuneracion' },
{ slug:'rrhh-finiquito', cat:'RRHH', p:'¿Qué pasa en el sistema cuando finiquito a alguien?',
  donde:'RRHH → Finiquito.',
  como:'Además del cálculo: da de baja sus descuentos internos, SUSPENDE su usuario con la fecha de término, cierra sus sesiones abiertas en el acto y genera la ODP del finiquito.',
  quien:'RRHH ejecuta; todo lo demás es automático.', kw:'finiquito termino baja desvinculacion' },
{ slug:'rrhh-asistencia', cat:'RRHH', p:'¿De dónde salen las marcas de asistencia?',
  donde:'Integración Workera (reloj control).',
  como:'Las marcas llegan del conector Workera; los atrasos alimentan RRHH.',
  quien:'Automático; RRHH revisa.', kw:'asistencia reloj marcas atrasos workera' },

/* ═══ ACADEMIA Y OTROS ═══ */
{ slug:'academia-cursos', cat:'Academia', p:'¿Dónde aprendo a usar los módulos?',
  donde:'Academia AutoFácil.',
  como:'Cursos por módulo con progreso individual, libros interactivos y este mismo buscador Dónde·Cómo·Quién.',
  quien:'Todos los usuarios.', href:'/academia', kw:'aprender curso capacitacion academia' },
{ slug:'midia-widgets', cat:'Academia', p:'¿Qué es "Mi Día"?',
  donde:'Mi Día (home personal).',
  como:'Widgets según tu perfil: pendientes, indicadores, cumpleaños, calendario.',
  quien:'Cada usuario ve el suyo.', kw:'mi dia widgets inicio personal' },
{ slug:'mando-tv', cat:'Academia', p:'¿Qué se muestra en las pantallas TV de la oficina?',
  donde:'/mando — Cuadro de Mando TV.',
  como:'Vista estilo NASA con los indicadores del negocio en vivo, pensada para pantalla completa.',
  quien:'Cuenta de propósito fijo con sesión extendida.', kw:'tv pantalla mando indicadores dashboard' },
{ slug:'tickets-ti', cat:'Academia', p:'¿Cómo pido soporte de TI?',
  donde:'Tickets TI.',
  como:'Se crea el ticket con su motivo; los SLA y el escalamiento son configurables.',
  quien:'Cualquier usuario crea; TI atiende.', kw:'soporte ticket ti problema ayuda computador' },
{ slug:'compliance-canal', cat:'Academia', p:'¿Dónde hago una denuncia (Ley Karin)?',
  donde:'Canal de Compliance.',
  como:'Denuncias anónimas o identificadas; las anónimas reciben un código para hacer seguimiento sin revelar identidad.',
  quien:'Cualquier persona; gestiona Compliance.', kw:'denuncia karin acoso anonima compliance' },
{ slug:'whatsapp-bot', cat:'Academia', p:'¿Qué hace el bot de WhatsApp "Facilito"?',
  donde:'WhatsApp oficial (Meta Cloud).',
  como:'Atiende consultas de clientes; las conversaciones quedan registradas.',
  quien:'Automático; configuración del área.', kw:'bot whatsapp facilito cliente chat' },
{ slug:'portal-cliente', cat:'Academia', p:'¿Cómo ve un cliente sus créditos?',
  donde:'Portal del Cliente (/mis-creditos).',
  como:'Entra con su RUT y un código OTP que le llega; ve sus operaciones y cuotas.',
  quien:'El cliente final (fuera del staff).', kw:'cliente portal mis creditos otp' },

/* ═══ SISTEMA Y PLATAFORMA ═══ */
{ slug:'sys-version', cat:'Sistema', p:'¿Cómo sé qué versión de la plataforma estoy usando?',
  donde:'Badge junto al logo (esquina superior izquierda de toda pantalla).',
  como:'La versión (ej. v177.0) sube con cada cambio; es la forma de confirmar que un arreglo ya llegó a producción tras el deploy.',
  quien:'Visible para todos.', kw:'version badge actualizacion deploy' },
{ slug:'sys-salud', cat:'Sistema', p:'¿Dónde veo si el sistema está sano?',
  donde:'Informe de Salud del Sistema + /api/health.',
  como:'Muestra base de datos, documentos (bucket), motores apagados/encendidos, uptime por servicio y costo de IA en vivo.',
  quien:'Administrador/TI.', kw:'salud health monitoreo uptime estado' },
{ slug:'sys-contingencia', cat:'Sistema', p:'¿Qué pasa si se cae el servidor principal?',
  donde:'Host de contingencia: afbs2.autofacilchile.cl.',
  como:'Existe un servidor de respaldo dormido con la MISMA base y las integraciones cargadas; se promueve con un comando según el runbook. Arranca en ~5 segundos.',
  quien:'Lo promueve TI/Administrador siguiendo el runbook.', kw:'caida render contingencia respaldo afbs2 emergencia' },
{ slug:'sys-respaldos', cat:'Sistema', p:'¿La información está respaldada?',
  donde:'Automático, tres copias.',
  como:'Base de datos: TiDB (1 día) + GitHub (30 días) + Google (90 días), cada noche. Documentos: bucket principal + copia en otra región + copia semanal fuera de Google.',
  quien:'Automático; restauración según runbook.', kw:'backup respaldo copia seguridad perdida' },
{ slug:'sys-documentos', cat:'Sistema', p:'¿Dónde quedan guardados los archivos que subo?',
  donde:'Bucket de documentos en la nube (no en la base de datos).',
  como:'Todo archivo subido va a almacenamiento dedicado con versionado: un borrado por error se puede revertir. La descarga es transparente desde cada pantalla.',
  quien:'Automático.', kw:'archivos donde guardan bucket nube pdf' },
{ slug:'sys-modo-dev', cat:'Sistema', p:'¿Por qué en pruebas los correos no llegan a los destinatarios reales?',
  donde:'Modo Desarrollo (staging).',
  como:'En ambientes de prueba TODO el correo se redirige a cuentas de prueba, a propósito, para no molestar a clientes reales.',
  quien:'Automático según el ambiente.', kw:'correo no llega staging prueba desarrollo' },
{ slug:'sys-pwa', cat:'Sistema', p:'¿Puedo instalar la plataforma como aplicación?',
  donde:'Desde el navegador (Chrome/Edge): Instalar aplicación.',
  como:'Es una PWA instalable; queda como app con su ícono, sin caché (siempre la versión vigente).',
  quien:'Cualquier usuario.', kw:'instalar app aplicacion escritorio celular' },
{ slug:'sys-reporteria', cat:'Sistema', p:'¿Cómo armo un reporte a medida?',
  donde:'Reportería → Diseño de Consulta.',
  como:'Constructor visual estilo Access: eliges fuente, campos, filtros y agrupaciones sin escribir SQL. También están los reportes Tailor Made ya armados.',
  quien:'Perfiles con acceso a Reportería.', href:'/reporteria/', kw:'reporte consulta diseño tailor made excel' },
{ slug:'sys-dashboard', cat:'Sistema', p:'¿De dónde salen los números del Dashboard?',
  donde:'Dashboard principal.',
  como:'Lee créditos + clientes en vivo, deduplicado por operación; el corte MAYOR/MENOR 200UF se calcula con la UF de la fecha de otorgamiento. Los filtros recalculan en pantalla.',
  quien:'Perfiles con el tab habilitado (config paramétrica por perfil).', href:'/dashboard/', kw:'dashboard numeros indicadores 200uf resumen' },
{ slug:'sys-cotizador', cat:'Sistema', p:'¿Dónde simulo un crédito rápido?',
  donde:'Simulador Rápido.',
  como:'Motor único de cotización (el mismo de la API pública): monto, plazo, tasa → cuota.',
  quien:'Todos los perfiles comerciales.', kw:'simular cotizar cuota calculo credito' },
{ slug:'sys-donde-curso', cat:'Sistema', p:'¿Cómo decido en qué financiera cursar una operación?',
  donde:'PWA ¿Dónde Curso? / Preferencia Financiera.',
  como:'Grilla por cuotas × saldo que compara financieras; si la diferencia es menor al 10%, dice "Decides Tú".',
  quien:'Ejecutivos comerciales.', kw:'donde curso financiera preferencia comparar autofin unidad' },
{ slug:'crm-campanas', cat:'Sistema', p:'¿Cómo lanzo una campaña a clientes?',
  donde:'CRM → Campañas (discador) y Campañas Masivas (correo/WhatsApp).',
  como:'El discador asigna llamadas a ejecutivos; las masivas envían por deciles con grupo de control para medir efecto real.',
  quien:'Comercial/CRM con el permiso.', kw:'campana discador llamadas masiva marketing deciles' },
{ slug:'digitacion-faltantes', cat:'Créditos', p:'¿Qué es la cola de Datos Faltantes?',
  donde:'Digitación → Datos Faltantes.',
  como:'Operaciones con campos incompletos entran a una cola; al tomar una se bloquea 20 minutos para que dos personas no la digiten a la vez.',
  quien:'Digitadores.', kw:'faltantes cola completar campos bloqueo' },
{ slug:'atencion-remota', cat:'Sistema', p:'¿Cómo atiendo a un dealer por chat con documentos?',
  donde:'Atención Remota.',
  como:'Chat en vivo con intercambio de documentos; el dealer entra por link o con su cuenta del portal.',
  quien:'Staff atiende; dealers externos participan.', kw:'chat remoto atencion dealer documentos' },
{ slug:'venta-cartera', cat:'Créditos', p:'¿Cómo se vende cartera de créditos?',
  donde:'Módulo Venta de Cartera.',
  como:'Selecciona créditos AUTOFACIL (stock + cuotas del mes) para venderlos a CFC; genera el detalle y su contabilización.',
  quien:'Gerencia/Finanzas.', kw:'vender cartera cfc cesion' },
{ slug:'previred-indicadores', cat:'RRHH', p:'¿De dónde salen los indicadores previsionales (AFP, salud)?',
  donde:'Indicadores Previred.',
  como:'Se obtienen automáticamente y la IA propone la actualización, pero SIEMPRE la aplica un humano tras revisar.',
  quien:'RRHH aprueba cada actualización.', kw:'previred afp salud topes indicadores previsional' },
{ slug:'certificados-qr', cat:'Sistema', p:'¿Cómo verifico que un certificado emitido por el sistema es auténtico?',
  donde:'El QR impreso en el certificado.',
  como:'Cada certificado queda registrado con su huella digital (hash); el QR lleva a la verificación pública del documento.',
  quien:'Cualquier persona con el QR.', kw:'certificado qr verificar autentico firma' },
{ slug:'wsp-bot-no-responde', cat:'Sistema', p:'¿Por qué el bot de WhatsApp no le responde a un cliente?',
  donde:'WhatsApp → la conversación; la configuración en WhatsApp → Configuración.',
  como:'Si la conversación está DERIVADA, el bot se calla a propósito para no hablarle por encima al ejecutivo que la tomó. Pasadas las horas configuradas sin actividad vuelve sola al bot y se suelta del ejecutivo; también puedes devolverla a mano desde la conversación. Si NINGÚN cliente recibe respuesta, el problema es otro: revisa que la URL del webhook en Meta apunte al dominio propio.',
  quien:'Ejecutivos de atención; el Administrador ajusta las horas.', kw:'whatsapp bot no responde derivada mudo webhook facilito' },
{ slug:'parque-crear', cat:'Dealers', p:'¿Cómo se crea un parque automotriz en el sistema?',
  donde:'Creación/Mantenedor de Dealer → Creación de Parque → "Nuevo parque".',
  como:'Sigue el MISMO circuito que la ficha de dealer: se llena la ficha (RUT, representante legal, contactos, cuenta), se envía a autorización (informes comerciales + análisis IA), la aprueban los niveles, se imprime, la firma el representante legal, se sube firmada y el analista cierra el caso — recién ahí el parque queda creado. Su arriendo y % de comisión se fijan en el mantenedor Arriendos y Comisiones Parque y Calle.',
  quien:'Ejecutivo crea la ficha; Análisis y Gerencia autorizan; el analista cierra.', kw:'parque crear ficha incorporacion nuevo automotriz' },
{ slug:'parque-cartola', cat:'Post Venta', p:'¿Cómo se le paga la comisión a un parque?',
  donde:'Post Venta → Emisión de Cartolas Parque; el pago en Comisiones Parques a Pagar.',
  como:'Las condiciones son las mismas que para el dealer. La cartola mensual del parque (comisión por cada crédito + arriendo) se Emite, se Aprueba y se Envía por correo al contacto de finanzas de su ficha con el total a facturar. El parque factura y la factura se registra en Cartolas Parque con cuadratura estricta: el monto debe ser exactamente el total de la cartola. Recién con eso se emite la ODP mensual y se paga. La contabilidad es automática: arriendo y comisión van a cuentas separadas al aprobar, y el pago rebaja el pasivo contra banco.',
  quien:'Post Venta emite y envía; quien tiene el permiso aprueba; Tesorería paga.', kw:'parque comision pagar cartola arriendo factura odp' },
{ slug:'parque-reversa', cat:'Post Venta', p:'Me equivoqué con la cartola o la ODP de un parque, ¿puedo deshacerlo?',
  donde:'Emisión de Cartolas Parque (pestaña Enviadas) y la misma pantalla del parque.',
  como:'Todo eslabón tiene reversa con motivo auditado: Reversar el envío quita solo CARTOLA ENVIADA (puedes reenviar); Anular ODP sirve mientras no esté pagada (el número queda anulado, nunca se reutiliza); Revertir pago deshace el pago y la ODP vuelve a "por pagar".',
  quien:'Quien tenga el permiso de cada acción; todo queda en Auditoría.', kw:'parque reversar anular odp cartola pago deshacer' },
{ slug:'endpoints-catalogo', cat:'Mantenedores', p:'¿Dónde veo todas las APIs internas del sistema y sus permisos?',
  donde:'Mantenedores → Catálogo de Endpoints.',
  como:'Es un inventario auto-generado del código en cada consulta (nunca se edita a mano): los ~1.300 endpoints con su método, ruta, si exigen sesión y qué permisos los gobiernan. Sirve como auditoría: lo rojo son escrituras sin permiso (cualquier usuario logueado podría ejecutarlas) y lo ámbar son rutas públicas, que deben ser deliberadas (login, webhooks, QR).',
  quien:'Solo Administrador (permiso mant_endpoints).', href:'/mantenedores/endpoints/',
  kw:'endpoints api internas catalogo rutas permisos inventario auditoria' },
];
